import {
  AUTHORING_SOURCE_ATTRIBUTE,
  AUTHORING_SOURCE_RESERVED,
  AUTHORING_SOURCE_RUNTIME_ACCESS_RESERVED,
  assertNoAuthoredSourceProvenance,
} from '../../editor-engine/source-provenance-policy.cjs'

export const AUTHORING_SOURCE_PROVENANCE_ATTRIBUTE = AUTHORING_SOURCE_ATTRIBUTE
export const AUTHORING_SOURCE_PROVENANCE_RESERVED = AUTHORING_SOURCE_RESERVED
export { AUTHORING_SOURCE_RUNTIME_ACCESS_RESERVED }
export { assertNoAuthoredSourceProvenance }
