import { NextResponse } from 'next/server'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { LockProfile } from '@/lib/effect/locks'
import { unsound } from './validate'

/** THE SEALED PROFILE, written back to the repo. Dev only: Grid Lab is the admin engine, and the file
 *  it writes is what production reads — there is no runtime store to drift from it. */
const PROFILE_FILE = join(process.cwd(), 'src', 'lib', 'effect', 'lock-profile.ts')

const HEADER = `// GENERATED by the Grid Lab — the 🔒 beside each dial writes this file through /api/dev/lock-profile.
// It is the repo's SEALED PROFILE: every locked value here overrides whatever a caller passes, in the
// Grid Lab and in production alike. Change it there, not here.
import type { LockProfile } from './locks'

export const LOCK_PROFILE: LockProfile = `

export async function POST(req: Request) {
  if (process.env.NODE_ENV === 'production') return NextResponse.json({ error: 'dev only' }, { status: 404 })
  try {
    const body: unknown = await req.json()
    const why = unsound(body)
    if (why) return NextResponse.json({ error: why }, { status: 400 })
    await writeFile(PROFILE_FILE, HEADER + JSON.stringify(body as LockProfile, null, 2) + '\n')
    return NextResponse.json({ saved: true })
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
