import { describe,expect,it } from 'vitest'
import { algebraicGeneratorProofs,certifySqrtQuadraticExpression,contourIdentity,sha256Text,validateCertifiedExpressionIdentity } from '../compute/identity'
import { approximateExact,compareExactToRational,quadraticRootsWithin,rational } from '../compute/exact-real'
import type { Contour } from '../spec'
const contour=(points:[number,number][],holes:Contour['holes']=[]):Contour=>({outer:{pts:points},holes})
describe('Wrap canonical identity',()=>{
  it('matches the SHA-256 known vector',()=>expect(sha256Text('abc')).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'))
  it('is stable for identical ordered bits and changes with order, content and holes',()=>{const a=contour([[0,0],[1,0],[0,1]]);expect(contourIdentity(a)).toBe(contourIdentity(a));expect(contourIdentity(a)).not.toBe(contourIdentity(contour([[1,0],[0,0],[0,1]])));expect(contourIdentity(a)).not.toBe(contourIdentity(contour([[0,0],[1,0],[0,1]],[{pts:[[.1,.1],[.2,.1],[.1,.2]]}])))})
  it('serializes, validates and replays a certified scale-coupled expression canonically',()=>{const scale=quadraticRootsWithin(rational(1),rational(-192),rational(8064),rational(129),rational(131))[0];const value=certifySqrtQuadraticExpression(scale,[rational(1),rational(-192),rational(9216)],rational(0));expect(approximateExact(value)).toBeCloseTo(24*Math.SQRT2,12);expect(compareExactToRational(value,rational(33))).toBe(1);expect(compareExactToRational(value,rational(34))).toBe(-1);expect(structuredClone(value)).toEqual(value);expect(certifySqrtQuadraticExpression(scale,[rational(1),rational(-192),rational(9216)],rational(0))).toEqual(value);if(!('expressionHash'in value))return;validateCertifiedExpressionIdentity(value);expect(()=>validateCertifiedExpressionIdentity({...value,expressionHash:'0'.repeat(64)})).toThrow();expect(()=>validateCertifiedExpressionIdentity({...value,proofId:'0'.repeat(64)})).toThrow();expect(()=>validateCertifiedExpressionIdentity({...value,isolating:[rational(0),rational(1)]})).toThrow();const expression=[...value.expression.slice(0,5),JSON.stringify(rational(100))];const expressionHash=sha256Text(JSON.stringify(expression));const proofId=sha256Text(JSON.stringify(['sqrt-quadratic-proof-v1',expressionHash]));expect(()=>validateCertifiedExpressionIdentity({...value,expression,expressionHash,proofId})).toThrow('certified expression bounds')})
  it('orders and deduplicates algebraic generators semantically',()=>{const a={semanticSourceIdentity:'a',definingPolynomial:['1','0','-2']},b={semanticSourceIdentity:'b',definingPolynomial:['1','0','-2']};const forward=algebraicGeneratorProofs([a,b,{...a,definingPolynomial:['2','0','-4']}]),reverse=algebraicGeneratorProofs([b,a]);expect(forward).toEqual(reverse);expect(forward).toHaveLength(2);expect(forward.map(x=>x.generatorIdentity)).toEqual([...forward.map(x=>x.generatorIdentity)].sort());expect(forward[0].generatorIdentity).not.toBe(forward[1].generatorIdentity)})
  it('rejects a repeated-factor defining polynomial instead of choosing a root',()=>{expect(()=>algebraicGeneratorProofs([{semanticSourceIdentity:'repeated',definingPolynomial:['1','-2','1']}])).toThrow('square-free')})
})
