/* This file is generated by npm run grid:catalogue:generate. Do not edit by hand. */
import type { GridJob, GridJobResult } from './grid'

export const GRID_STATIC_CATALOGUE_CACHE_VERSION = 16 as const
export const GRID_STATIC_CATALOGUE_POLICY_SIGNATURE = "{\"circleTessellation\":{\"minimumPoints\":96},\"constructionQuantumMM\":0.00005,\"defaultLaw\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"defaultMarginMM\":12,\"focalRamp2MM\":200,\"focalSizeMM\":100,\"holdReachMM\":48,\"manufacturingOffsetArcToleranceMM\":0.025,\"minAnchors\":2,\"modes\":{\"autoBySource\":{\"freeform\":[{\"pattern\":\"standard\",\"pitchMM\":48},{\"pattern\":\"standard\",\"pitchMM\":96},{\"pattern\":\"diamond\",\"pitchMM\":48},{\"pattern\":\"diamond\",\"pitchMM\":96},{\"pattern\":\"quincunx\",\"pitchMM\":96}],\"product\":[{\"pattern\":\"standard\",\"pitchMM\":48},{\"pattern\":\"standard\",\"pitchMM\":96}]},\"diamond\":[{\"pattern\":\"diamond\",\"pitchMM\":48},{\"pattern\":\"diamond\",\"pitchMM\":96}],\"quincunx\":[{\"pattern\":\"quincunx\",\"pitchMM\":96}],\"standard\":[{\"pattern\":\"standard\",\"pitchMM\":48},{\"pattern\":\"standard\",\"pitchMM\":96}]},\"paddingFloorMM\":10,\"pitchesMM\":[48,96],\"preparedContourEpsilonMM\":0.005,\"randomShapeMaxMM\":180,\"targetAnchors\":4}" as const
export const GRID_STATIC_CATALOGUE_ENTRIES = [
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "square"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"square\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "S",
          "points": 4,
          "sizeMM": 68,
          "baseSizeMM": 68,
          "designSizeMM": 68,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 68,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 8,
          "sizeMM": 116,
          "baseSizeMM": 116,
          "designSizeMM": 116,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 116,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                1,
                0
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 12,
          "sizeMM": 164,
          "baseSizeMM": 164,
          "designSizeMM": 164,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 164,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                1,
                0
              ],
              [
                1,
                3
              ],
              [
                2,
                0
              ],
              [
                2,
                3
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ]
            ]
          }
        },
        {
          "label": "XL",
          "points": 16,
          "sizeMM": 212,
          "baseSizeMM": 212,
          "designSizeMM": 212,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 212,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                0,
                4
              ],
              [
                1,
                0
              ],
              [
                1,
                4
              ],
              [
                2,
                0
              ],
              [
                2,
                4
              ],
              [
                3,
                0
              ],
              [
                3,
                4
              ],
              [
                4,
                0
              ],
              [
                4,
                1
              ],
              [
                4,
                2
              ],
              [
                4,
                3
              ],
              [
                4,
                4
              ]
            ]
          }
        },
        {
          "label": "2XL",
          "points": 20,
          "sizeMM": 260,
          "baseSizeMM": 260,
          "designSizeMM": 260,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 260,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                0,
                4
              ],
              [
                0,
                5
              ],
              [
                1,
                0
              ],
              [
                1,
                5
              ],
              [
                2,
                0
              ],
              [
                2,
                5
              ],
              [
                3,
                0
              ],
              [
                3,
                5
              ],
              [
                4,
                0
              ],
              [
                4,
                5
              ],
              [
                5,
                0
              ],
              [
                5,
                1
              ],
              [
                5,
                2
              ],
              [
                5,
                3
              ],
              [
                5,
                4
              ],
              [
                5,
                5
              ]
            ]
          }
        },
        {
          "label": "3XL",
          "points": 24,
          "sizeMM": 308,
          "baseSizeMM": 308,
          "designSizeMM": 308,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 308,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                0,
                4
              ],
              [
                0,
                5
              ],
              [
                0,
                6
              ],
              [
                1,
                0
              ],
              [
                1,
                6
              ],
              [
                2,
                0
              ],
              [
                2,
                6
              ],
              [
                3,
                0
              ],
              [
                3,
                6
              ],
              [
                4,
                0
              ],
              [
                4,
                6
              ],
              [
                5,
                0
              ],
              [
                5,
                6
              ],
              [
                6,
                0
              ],
              [
                6,
                1
              ],
              [
                6,
                2
              ],
              [
                6,
                3
              ],
              [
                6,
                4
              ],
              [
                6,
                5
              ],
              [
                6,
                6
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "square"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"square\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "S",
          "points": 4,
          "sizeMM": 116,
          "baseSizeMM": 116,
          "designSizeMM": 116,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 116,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 8,
          "sizeMM": 212,
          "baseSizeMM": 212,
          "designSizeMM": 212,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 212,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                1,
                0
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 12,
          "sizeMM": 308,
          "baseSizeMM": 308,
          "designSizeMM": 308,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 308,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              10,
              10
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                1,
                0
              ],
              [
                1,
                3
              ],
              [
                2,
                0
              ],
              [
                2,
                3
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "circle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"circle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "S",
          "points": 2,
          "sizeMM": 68,
          "baseSizeMM": 68,
          "designSizeMM": 68,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 68,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              34,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 4,
          "sizeMM": 116,
          "baseSizeMM": 116,
          "designSizeMM": 116,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 116,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              10,
              58
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                -1
              ],
              [
                1,
                1
              ],
              [
                2,
                0
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 8,
          "sizeMM": 172,
          "baseSizeMM": 172,
          "designSizeMM": 172,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 164,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              14,
              62
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                -1
              ],
              [
                1,
                2
              ],
              [
                2,
                -1
              ],
              [
                2,
                2
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ]
            ]
          }
        },
        {
          "label": "XL",
          "points": 8,
          "sizeMM": 236,
          "baseSizeMM": 236,
          "designSizeMM": 236,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 212,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              22,
              70
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                2
              ],
              [
                1,
                -1
              ],
              [
                1,
                3
              ],
              [
                3,
                -1
              ],
              [
                3,
                3
              ],
              [
                4,
                0
              ],
              [
                4,
                2
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "circle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"circle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "S",
          "points": 4,
          "sizeMM": 156,
          "baseSizeMM": 156,
          "designSizeMM": 156,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 116,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              30,
              30
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "triangle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"triangle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "S",
          "points": 2,
          "sizeMM": 92,
          "baseSizeMM": 92,
          "designSizeMM": 92,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 68,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              46,
              10
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "triangle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"triangle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": []
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "diamondShape"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"diamondShape\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "S",
          "points": 2,
          "sizeMM": 78,
          "baseSizeMM": 78,
          "designSizeMM": 78,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 68,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              39,
              15
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 4,
          "sizeMM": 126,
          "baseSizeMM": 126,
          "designSizeMM": 126,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 116,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              15,
              63
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                -1
              ],
              [
                1,
                1
              ],
              [
                2,
                0
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 6,
          "sizeMM": 174,
          "baseSizeMM": 174,
          "designSizeMM": 174,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 164,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              39,
              63
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                -1
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ]
            ]
          }
        },
        {
          "label": "XL",
          "points": 8,
          "sizeMM": 222,
          "baseSizeMM": 222,
          "designSizeMM": 222,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 212,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              15,
              111
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                -1
              ],
              [
                1,
                1
              ],
              [
                2,
                -2
              ],
              [
                2,
                2
              ],
              [
                3,
                -1
              ],
              [
                3,
                1
              ],
              [
                4,
                0
              ]
            ]
          }
        },
        {
          "label": "2XL",
          "points": 10,
          "sizeMM": 270,
          "baseSizeMM": 270,
          "designSizeMM": 270,
          "marginMM": 0,
          "frameBufferMM": 0,
          "gridExtentMM": 260,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              39,
              111
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                -1
              ],
              [
                1,
                2
              ],
              [
                2,
                -2
              ],
              [
                2,
                3
              ],
              [
                3,
                -1
              ],
              [
                3,
                2
              ],
              [
                4,
                0
              ],
              [
                4,
                1
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "diamondShape"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"frameBufferMM\":0,\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"diamondShape\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": []
    }
  }
] as const satisfies ReadonlyArray<{
  job: GridJob
  result: GridJobResult
}>
