/* This file is generated by npm run grid:catalogue:generate. Do not edit by hand. */
import type { GridJob, GridJobResult } from './grid'

export const GRID_STATIC_CATALOGUE_CACHE_VERSION = 16 as const
export const GRID_STATIC_CATALOGUE_POLICY_SIGNATURE = "{\"circleTessellation\":{\"minimumPoints\":96},\"constructionQuantumMM\":0.00005,\"defaultLaw\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"defaultMarginMM\":12,\"focalRamp2MM\":200,\"focalSizeMM\":100,\"holdReachMM\":48,\"manufacturingOffsetArcToleranceMM\":0.025,\"minAnchors\":2,\"modes\":{\"autoBySource\":{\"freeform\":[{\"pattern\":\"standard\",\"pitchMM\":48},{\"pattern\":\"standard\",\"pitchMM\":96},{\"pattern\":\"diamond\",\"pitchMM\":48},{\"pattern\":\"diamond\",\"pitchMM\":96},{\"pattern\":\"quincunx\",\"pitchMM\":96}],\"product\":[{\"pattern\":\"standard\",\"pitchMM\":48},{\"pattern\":\"standard\",\"pitchMM\":96}]},\"diamond\":[{\"pattern\":\"diamond\",\"pitchMM\":48},{\"pattern\":\"diamond\",\"pitchMM\":96}],\"quincunx\":[{\"pattern\":\"quincunx\",\"pitchMM\":96}],\"standard\":[{\"pattern\":\"standard\",\"pitchMM\":48},{\"pattern\":\"standard\",\"pitchMM\":96}]},\"paddingFloorMM\":10,\"pitchesMM\":[48,96],\"preparedContourEpsilonMM\":0.005,\"randomShapeMaxMM\":180,\"targetAnchors\":4}" as const
export const GRID_STATIC_CATALOGUE_ENTRIES = [
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "square"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"square\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 22,
          "designSizeMM": 22,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        },
        {
          "label": "S",
          "points": 4,
          "sizeMM": 70,
          "designSizeMM": 70,
          "marginMM": 0,
          "gridExtentMM": 70,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 9,
          "sizeMM": 118,
          "designSizeMM": 118,
          "marginMM": 0,
          "gridExtentMM": 118,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 16,
          "sizeMM": 166,
          "designSizeMM": 166,
          "marginMM": 0,
          "gridExtentMM": 166,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                1,
                3
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ],
              [
                2,
                3
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ]
            ]
          }
        },
        {
          "label": "XL",
          "points": 25,
          "sizeMM": 214,
          "designSizeMM": 214,
          "marginMM": 0,
          "gridExtentMM": 214,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                0,
                4
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                1,
                3
              ],
              [
                1,
                4
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ],
              [
                2,
                3
              ],
              [
                2,
                4
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ],
              [
                3,
                4
              ],
              [
                4,
                0
              ],
              [
                4,
                1
              ],
              [
                4,
                2
              ],
              [
                4,
                3
              ],
              [
                4,
                4
              ]
            ]
          }
        },
        {
          "label": "2XL",
          "points": 36,
          "sizeMM": 262,
          "designSizeMM": 262,
          "marginMM": 0,
          "gridExtentMM": 262,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                0,
                4
              ],
              [
                0,
                5
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                1,
                3
              ],
              [
                1,
                4
              ],
              [
                1,
                5
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ],
              [
                2,
                3
              ],
              [
                2,
                4
              ],
              [
                2,
                5
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ],
              [
                3,
                4
              ],
              [
                3,
                5
              ],
              [
                4,
                0
              ],
              [
                4,
                1
              ],
              [
                4,
                2
              ],
              [
                4,
                3
              ],
              [
                4,
                4
              ],
              [
                4,
                5
              ],
              [
                5,
                0
              ],
              [
                5,
                1
              ],
              [
                5,
                2
              ],
              [
                5,
                3
              ],
              [
                5,
                4
              ],
              [
                5,
                5
              ]
            ]
          }
        },
        {
          "label": "3XL",
          "points": 49,
          "sizeMM": 310,
          "designSizeMM": 310,
          "marginMM": 0,
          "gridExtentMM": 310,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                0,
                4
              ],
              [
                0,
                5
              ],
              [
                0,
                6
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                1,
                3
              ],
              [
                1,
                4
              ],
              [
                1,
                5
              ],
              [
                1,
                6
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ],
              [
                2,
                3
              ],
              [
                2,
                4
              ],
              [
                2,
                5
              ],
              [
                2,
                6
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ],
              [
                3,
                4
              ],
              [
                3,
                5
              ],
              [
                3,
                6
              ],
              [
                4,
                0
              ],
              [
                4,
                1
              ],
              [
                4,
                2
              ],
              [
                4,
                3
              ],
              [
                4,
                4
              ],
              [
                4,
                5
              ],
              [
                4,
                6
              ],
              [
                5,
                0
              ],
              [
                5,
                1
              ],
              [
                5,
                2
              ],
              [
                5,
                3
              ],
              [
                5,
                4
              ],
              [
                5,
                5
              ],
              [
                5,
                6
              ],
              [
                6,
                0
              ],
              [
                6,
                1
              ],
              [
                6,
                2
              ],
              [
                6,
                3
              ],
              [
                6,
                4
              ],
              [
                6,
                5
              ],
              [
                6,
                6
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "square"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"square\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 22,
          "designSizeMM": 22,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        },
        {
          "label": "S",
          "points": 4,
          "sizeMM": 118,
          "designSizeMM": 118,
          "marginMM": 0,
          "gridExtentMM": 118,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 8,
          "sizeMM": 214,
          "designSizeMM": 214,
          "marginMM": 0,
          "gridExtentMM": 214,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                1,
                0
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 12,
          "sizeMM": 310,
          "designSizeMM": 310,
          "marginMM": 0,
          "gridExtentMM": 310,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              11,
              11
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                0,
                2
              ],
              [
                0,
                3
              ],
              [
                1,
                0
              ],
              [
                1,
                3
              ],
              [
                2,
                0
              ],
              [
                2,
                3
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "circle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"circle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 24,
          "designSizeMM": 24,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              12,
              12
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        },
        {
          "label": "S",
          "points": 2,
          "sizeMM": 72,
          "designSizeMM": 72,
          "marginMM": 0,
          "gridExtentMM": 70,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              36,
              12
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 5,
          "sizeMM": 120,
          "designSizeMM": 120,
          "marginMM": 0,
          "gridExtentMM": 118,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              12,
              60
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                -1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                2,
                0
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 8,
          "sizeMM": 168,
          "designSizeMM": 168,
          "marginMM": 0,
          "gridExtentMM": 166,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              36,
              60
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                -1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ]
            ]
          }
        },
        {
          "label": "XL",
          "points": 29,
          "sizeMM": 310,
          "designSizeMM": 310,
          "marginMM": 0,
          "gridExtentMM": 310,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              11,
              155
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                -2
              ],
              [
                1,
                -1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                2,
                -2
              ],
              [
                2,
                -1
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ],
              [
                2,
                2
              ],
              [
                3,
                -3
              ],
              [
                3,
                -2
              ],
              [
                3,
                -1
              ],
              [
                3,
                0
              ],
              [
                3,
                1
              ],
              [
                3,
                2
              ],
              [
                3,
                3
              ],
              [
                4,
                -2
              ],
              [
                4,
                -1
              ],
              [
                4,
                0
              ],
              [
                4,
                1
              ],
              [
                4,
                2
              ],
              [
                5,
                -2
              ],
              [
                5,
                -1
              ],
              [
                5,
                0
              ],
              [
                5,
                1
              ],
              [
                5,
                2
              ],
              [
                6,
                0
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "circle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"circle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 24,
          "designSizeMM": 24,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              12,
              12
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        },
        {
          "label": "S",
          "points": 4,
          "sizeMM": 158,
          "designSizeMM": 158,
          "marginMM": 0,
          "gridExtentMM": 118,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              31,
              31
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "triangle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"triangle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 40,
          "designSizeMM": 40,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              20,
              11.547
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        },
        {
          "label": "S",
          "points": 5,
          "sizeMM": 150,
          "designSizeMM": 150,
          "marginMM": 0,
          "gridExtentMM": 118,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              27,
              11
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "triangle"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"triangle\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 40,
          "designSizeMM": 40,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              20,
              11.547
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "diamondShape"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "standard",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"standard\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"diamondShape\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 32,
          "designSizeMM": 32,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              16,
              16
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        },
        {
          "label": "S",
          "points": 2,
          "sizeMM": 80,
          "designSizeMM": 80,
          "marginMM": 0,
          "gridExtentMM": 70,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              40,
              16
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ]
            ]
          }
        },
        {
          "label": "M",
          "points": 5,
          "sizeMM": 128,
          "designSizeMM": 128,
          "marginMM": 0,
          "gridExtentMM": 118,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              16,
              64
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                1,
                -1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                2,
                0
              ]
            ]
          }
        },
        {
          "label": "L",
          "points": 8,
          "sizeMM": 176,
          "designSizeMM": 176,
          "marginMM": 0,
          "gridExtentMM": 166,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 48,
            "originMM": [
              40,
              64
            ],
            "basisMM": [
              [
                48,
                0
              ],
              [
                0,
                48
              ]
            ],
            "population": [
              [
                0,
                0
              ],
              [
                0,
                1
              ],
              [
                1,
                -1
              ],
              [
                1,
                0
              ],
              [
                1,
                1
              ],
              [
                1,
                2
              ],
              [
                2,
                0
              ],
              [
                2,
                1
              ]
            ]
          }
        }
      ]
    }
  },
  {
    "job": {
      "operation": "ladder",
      "recipe": {
        "kind": "standard",
        "shape": "diamondShape"
      },
      "mode": "auto",
      "options": {
        "source": "std",
        "density": "light",
        "center": "centroid"
      }
    },
    "result": {
      "operation": "ladder",
      "key": "{\"body\":{\"law\":{\"frameMM\":1,\"maxRungMM\":310,\"maxTestedMM\":214,\"paddingMM\":10},\"mode\":\"auto\",\"options\":{\"center\":\"centroid\",\"density\":\"light\",\"pitchMM\":null,\"source\":\"std\"},\"recipe\":{\"kind\":\"standard\",\"shape\":\"diamondShape\"}},\"cacheVersion\":16,\"operation\":\"ladder\",\"policy\":\"{\\\"circleTessellation\\\":{\\\"minimumPoints\\\":96},\\\"constructionQuantumMM\\\":0.00005,\\\"defaultLaw\\\":{\\\"frameMM\\\":1,\\\"maxRungMM\\\":310,\\\"maxTestedMM\\\":214,\\\"paddingMM\\\":10},\\\"defaultMarginMM\\\":12,\\\"focalRamp2MM\\\":200,\\\"focalSizeMM\\\":100,\\\"holdReachMM\\\":48,\\\"manufacturingOffsetArcToleranceMM\\\":0.025,\\\"minAnchors\\\":2,\\\"modes\\\":{\\\"autoBySource\\\":{\\\"freeform\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96},{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"product\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"diamond\\\":[{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"diamond\\\",\\\"pitchMM\\\":96}],\\\"quincunx\\\":[{\\\"pattern\\\":\\\"quincunx\\\",\\\"pitchMM\\\":96}],\\\"standard\\\":[{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":48},{\\\"pattern\\\":\\\"standard\\\",\\\"pitchMM\\\":96}]},\\\"paddingFloorMM\\\":10,\\\"pitchesMM\\\":[48,96],\\\"preparedContourEpsilonMM\\\":0.005,\\\"randomShapeMaxMM\\\":180,\\\"targetAnchors\\\":4}\"}",
      "value": [
        {
          "label": "ONE",
          "points": 1,
          "sizeMM": 32,
          "designSizeMM": 32,
          "marginMM": 0,
          "gridExtentMM": 22,
          "visible": true,
          "construction": {
            "pattern": "standard",
            "pitchMM": 96,
            "originMM": [
              16,
              16
            ],
            "basisMM": [
              [
                96,
                0
              ],
              [
                0,
                96
              ]
            ],
            "population": [
              [
                0,
                0
              ]
            ]
          }
        }
      ]
    }
  }
] as const satisfies ReadonlyArray<{
  job: GridJob
  result: GridJobResult
}>
