// GENERATED by the Grid Lab — the 🔒 beside each dial writes this file through /api/dev/lock-profile.
// It is the repo's SEALED PROFILE: every locked value here overrides whatever a caller passes, in the
// Grid Lab and in production alike. Change it there, not here.
import type { LockProfile } from './locks'

export const LOCK_PROFILE: LockProfile = {
  "version": 1,
  "locks": {
    "edgePaddingMM": {
      "value": 0,
      "locked": false
    },
    "paddingRadiusMM": {
      "value": 11,
      "locked": false
    }
  }
}
