/** Generated by scripts/build.mjs. The hash covers every executable .js file in
 * this package except artifact-manifest.js itself, avoiding a self-referential digest. */
export const COMPUTE_ARTIFACT_ID = "geometry-compute-ts-fixed-v1";
export const COMPUTE_ARTIFACT_HASH = "206d2b177120565b1b206383ab23b7c15f2695835cfbd3c7b02946e4df9b4d4d";
