/** Generated by scripts/build.mjs. The hash covers every executable .js file in
 * this package except artifact-manifest.js itself, avoiding a self-referential digest. */
export const COMPUTE_ARTIFACT_ID = "geometry-compute-ts-fixed-v1";
export const COMPUTE_ARTIFACT_HASH = "6f8b50133e58950863c23ab87cb19fe63eb6ffe1197502afea3549525337de67";
