/** Generated by scripts/build.mjs. The hash covers every executable .js file in
 * this package except artifact-manifest.js itself, avoiding a self-referential digest. */
export const COMPUTE_ARTIFACT_ID = "geometry-compute-ts-fixed-v1";
export const COMPUTE_ARTIFACT_HASH = "68a1d365d0d78e81d1bd55cbdabc53b31b26e61ae11478ed51319b9fcbf4e367";
