import { NextResponse } from 'next/server'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { LibraryReleaseState } from '@/lib/effect/library'
import { unsound } from './validate'

/** THE LIBRARY'S RELEASE STATE, written back to the repo. Dev only: the Grid Lab is the admin and the
 *  file it writes is what ships — there is no runtime store to drift from it. */
const STATE_FILE = join(process.cwd(), 'src', 'lib', 'effect', 'library', 'release-state.ts')

const HEADER = `// GENERATED by the Grid Lab — Library → Band "Edit" and the record "release" toggle write this file
// through /api/dev/library-release. It is the repo's record of what the Library shows and what is
// released to presets; edit it there, not here.
import type { LibraryReleaseState } from './release'

export const LIBRARY_RELEASE_STATE: LibraryReleaseState = `

export async function POST(req: Request) {
  if (process.env.NODE_ENV === 'production') return NextResponse.json({ error: 'dev only' }, { status: 404 })
  try {
    const body: unknown = await req.json()
    const why = unsound(body)
    if (why) return NextResponse.json({ error: why }, { status: 400 })
    const state = body as LibraryReleaseState
    await writeFile(STATE_FILE, HEADER + JSON.stringify(state, null, 2) + '\n')
    return NextResponse.json({ saved: true })
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
