// Generated by figma-to-code — deterministic, do not hand-edit structure (edit via react-figma).
import styles from './fixture-board.module.css';

export default function FixtureBoard() {
  return (
    <div className={styles.fixtureBoard}>
      <div className={styles.fxTextWrap}>
        <span className={styles.multiLineWrappingTextFixtureThatMustBreakAcrossSeveralLinesExactlyLikeFigmaDoes}>Multi line wrapping text fixture that must break across several lines exactly like Figma does</span>
      </div>
      <div className={styles.fxTextTruncate}>
        <span className={styles.truncatedTextFixtureThatIsFarTooLongToFit}>Truncated text fixture that is far too long to fit</span>
      </div>
      <div className={styles.fxSpaceBetween}>
        <div className={styles.rectangle} />
        <div className={styles.rectangle2} />
        <div className={styles.rectangle3} />
      </div>
      <div className={styles.fxNegativeGap}>
        <svg className={styles.ellipse} width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="14" cy="14" r="14" fill="#E65966"/>
</svg>

        <svg className={styles.ellipse2} width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="14" cy="14" r="14" fill="#598CE6"/>
</svg>

        <svg className={styles.ellipse3} width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="14" cy="14" r="14" fill="#E65966"/>
</svg>

        <svg className={styles.ellipse4} width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="14" cy="14" r="14" fill="#598CE6"/>
</svg>

      </div>
      <div className={styles.fxWrap}>
        <div className={styles.rectangle4} />
        <div className={styles.rectangle5} />
        <div className={styles.rectangle6} />
        <div className={styles.rectangle7} />
        <div className={styles.rectangle8} />
        <div className={styles.rectangle9} />
        <div className={styles.rectangle10} />
      </div>
      <div className={styles.fxAbsolute}>
        <div className={styles.rectangle11} />
        <div className={styles.rectangle12} />
      </div>
      <div className={styles.fxRotate30}>
        <div className={styles.rectangle13} />
      </div>
      <div className={styles.fxGradients}>
        <div className={styles.fxRadial} />
        <div className={styles.fxAngular} />
        <div className={styles.fxLinear} />
      </div>
      <div className={styles.fxStrokes}>
        <div className={styles.fxStrokePerside} />
        <div className={styles.fxStrokeOutside} />
        <div className={styles.fxStrokeCenter} />
      </div>
      <div className={styles.fxEffectStack} />
      <div className={styles.fxOpacityBlend} />
      <div className={styles.fxRadiusMixed} />
      <div className={styles.fxGradientRing} />
    </div>
  );
}
