// Generated by figma-to-code — route wrapper (SPEC §3.1 output placement).
import './fonts.css';
import FixtureBoard from './FixtureBoard';

export default function Page() {
  return <FixtureBoard />;
}
