// Generated by figma-to-code — route wrapper (SPEC §3.1 output placement).
import './fonts.css';
import './theme.css';
import MotherV2 from './MotherV2';

export default function Page() {
  return <MotherV2 />;
}
