import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function run(command, args) {
  const result = spawnSync(command, args, { cwd: root, stdio: 'inherit', shell: false });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

async function executableDigest(distRoot) {
  const files = [];
  async function walk(dir) {
    for (const name of (await readdir(dir)).sort()) {
      const path = join(dir, name);
      const info = await stat(path);
      if (info.isDirectory()) await walk(path);
      else if (path.endsWith('.js') && name !== 'artifact-manifest.js') files.push(path);
    }
  }
  await walk(distRoot);
  const hash = createHash('sha256');
  for (const path of files.sort()) {
    hash.update(relative(distRoot, path).replaceAll('\\', '/'));
    hash.update('\0');
    hash.update(await readFile(path));
    hash.update('\0');
  }
  return hash.digest('hex');
}

async function writeArtifactSource(path, idName, hashName, id, hash) {
  const content = `/** Generated by scripts/build.mjs. The hash covers every executable .js file in\n * this package except artifact-manifest.js itself, avoiding a self-referential digest. */\nexport const ${idName} = ${JSON.stringify(id)};\nexport const ${hashName} = ${JSON.stringify(hash)};\n`;
  await writeFile(path, content);
}

run(process.execPath, ['scripts/link-workspaces.mjs']);

// Geometry two-pass build: compile, hash executable output excluding the manifest,
// inject the hash, compile again, and verify the digest is stable.
run('tsc', ['-p', 'packages/geometry-compute/tsconfig.json']);
let computeHash = await executableDigest(resolve(root, 'packages/geometry-compute/dist'));
await writeArtifactSource(
  resolve(root, 'packages/geometry-compute/src/artifact-manifest.ts'),
  'COMPUTE_ARTIFACT_ID', 'COMPUTE_ARTIFACT_HASH', 'geometry-compute-ts-fixed-v1', computeHash
);
run('tsc', ['-p', 'packages/geometry-compute/tsconfig.json']);
const computeHashCheck = await executableDigest(resolve(root, 'packages/geometry-compute/dist'));
if (computeHashCheck !== computeHash) throw new Error(`Compute artifact digest changed after injection: ${computeHash} -> ${computeHashCheck}`);

// Logic two-pass build, after Compute is available through the workspace link.
run('tsc', ['-p', 'packages/magnetic-logic/tsconfig.json']);
let logicHash = await executableDigest(resolve(root, 'packages/magnetic-logic/dist'));
await writeArtifactSource(
  resolve(root, 'packages/magnetic-logic/src/artifact-manifest.ts'),
  'LOGIC_ARTIFACT_ID', 'LOGIC_ARTIFACT_HASH', 'magnetic-logic-ts-v1', logicHash
);
run('tsc', ['-p', 'packages/magnetic-logic/tsconfig.json']);
const logicHashCheck = await executableDigest(resolve(root, 'packages/magnetic-logic/dist'));
if (logicHashCheck !== logicHash) throw new Error(`Logic artifact digest changed after injection: ${logicHash} -> ${logicHashCheck}`);

run('tsc', ['-p', 'packages/magnetic-next/tsconfig.json']);
run('tsc', ['-p', 'examples/cli-demo/tsconfig.json']);
run(process.execPath, ['scripts/export-profiles.mjs']);

console.log(JSON.stringify({ computeArtifactHash: computeHash, logicArtifactHash: logicHash }, null, 2));
