// GENERATED by pull-ds-tokens.mjs — do not edit. Source: the Figma file.
export const RESOLVED = {
 "fileKey": "Qdb9Kx98afJHxaCGAIxoMC",
 "pulledAtFileVersion": null,
 "tokens": [
  {
   "name": "text/primary",
   "binding": "brand/black",
   "description": "🔒 LOCKED · text/ v2.3.2 — The default text voice — body, headings, controls.",
   "L": "#071013",
   "D": "#fafafa"
  },
  {
   "name": "text/primary/perma",
   "binding": "brand/black/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 — Primary voice, light-world reading pinned — text on constant-light surfaces.",
   "L": "#071013",
   "D": "#071013"
  },
  {
   "name": "text/primary/inverse-perma",
   "binding": "brand/white/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 — Primary voice, dark-world reading pinned — text on constant-dark surfaces: chrome, the constant button, the ink panel.",
   "L": "#fafafa",
   "D": "#fafafa"
  },
  {
   "name": "text/primary/inverse",
   "binding": "brand/white",
   "description": "🔒 LOCKED · text/ v2.3.2 — Primary voice, opposite of theme — text on surfaces that invert (the flipping button).",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "text/primary/subtle",
   "binding": "neutral/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — Supporting register — captions, labels, meta.",
   "L": "#60646c",
   "D": "#b0b4ba"
  },
  {
   "name": "text/primary/subtle-inverse-perma",
   "binding": "brand/white/l-alpha/9",
   "description": "🔒 LOCKED · text/ v2.3.2 — Supporting register, dark-world reading pinned.",
   "L": "#fafafab2",
   "D": "#fafafab2"
  },
  {
   "name": "text/primary/subtle-perma",
   "binding": "brand/black/l-alpha/9",
   "description": "🔒 LOCKED · text/ v2.3.2 — Supporting register, light-world reading pinned.",
   "L": "#071013b2",
   "D": "#071013b2"
  },
  {
   "name": "text/primary/subtle-inverse",
   "binding": "brand/white/alpha/9",
   "description": "🔒 LOCKED · text/ v2.3.2 — Supporting register, opposite of theme — secondary text on inverse surfaces.",
   "L": "#fafafab2",
   "D": "#071013b2"
  },
  {
   "name": "text/max",
   "binding": "base/black",
   "description": "🔒 LOCKED · text/ v2.3.2 — True maximum contrast, follows theme. Absolutes and media only — UI text uses primary.",
   "L": "#000000",
   "D": "#ffffff"
  },
  {
   "name": "text/max/inverse",
   "binding": "base/white",
   "description": "🔒 LOCKED · text/ v2.3.2 — Maximum contrast, opposite of theme — text on surfaces that invert against the theme.",
   "L": "#ffffff",
   "D": "#000000"
  },
  {
   "name": "text/max/perma",
   "binding": "base/black/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 — Maximum contrast, light-world reading pinned — never role-flips. Media & absolutes.",
   "L": "#000000",
   "D": "#000000"
  },
  {
   "name": "text/max/inverse-perma",
   "binding": "base/white/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 — Maximum contrast, dark-world reading pinned — photo text; luminance-picked with max-perma.",
   "L": "#ffffff",
   "D": "#ffffff"
  },
  {
   "name": "text/system/disabled",
   "binding": "neutral/8",
   "description": "🔒 LOCKED · text/ v2.3.2 — Unavailable controls. Law: never on selectable options.",
   "L": "#b9bbc6",
   "D": "#5a6169"
  },
  {
   "name": "text/system/placeholder",
   "binding": "neutral/9",
   "description": "🔒 LOCKED · text/ v2.3.2 — Input hints — the placeholder exception: quieter than readable tiers by design, vanishes on input.",
   "L": "#8b8d98",
   "D": "#696e77"
  },
  {
   "name": "text/system/error",
   "binding": "error/12",
   "description": "🔒 LOCKED · text/ v2.3.2 — Validation and destructive copy.",
   "L": "#601f1e",
   "D": "#ffcfcb"
  },
  {
   "name": "text/system/warning",
   "binding": "warning/12",
   "description": "🔒 LOCKED · text/ v2.3.2 — Caution copy.",
   "L": "#403f19",
   "D": "#f2f1b3"
  },
  {
   "name": "text/system/success",
   "binding": "success/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — Confirmation copy.",
   "L": "#007d1c",
   "D": "#57d574"
  },
  {
   "name": "text/brand/primary",
   "binding": "brand/1/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — First brand colour as text — links, active labels, accents.",
   "L": "#1170a1",
   "D": "#73c4f8"
  },
  {
   "name": "text/brand/primary-subtle",
   "binding": "brand/1/10",
   "description": "🔒 LOCKED · text/ v2.3.2 — First brand colour, decorative register — below body-text contrast; never reading copy.",
   "L": "#287fb0",
   "D": "#287fb0"
  },
  {
   "name": "text/brand/primary-strong",
   "binding": "brand/1/12",
   "description": "🔒 LOCKED · text/ v2.3.2 — First brand colour, emphasis register — and the text voice on its own tints (on-colour law).",
   "L": "#19394d",
   "D": "#c4ecff"
  },
  {
   "name": "text/brand/secondary",
   "binding": "brand/2/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — Second brand colour as text.",
   "L": "#517700",
   "D": "#98cb46"
  },
  {
   "name": "text/brand/tertiary",
   "binding": "brand/3/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — Third brand colour as text.",
   "L": "#6940b9",
   "D": "#bda2ff"
  },
  {
   "name": "text/brand/primary-inverse",
   "binding": "brand/1/inverse/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — First brand colour, opposite of theme — coloured text on inverse surfaces.",
   "L": "#73c4f8",
   "D": "#1170a1"
  },
  {
   "name": "text/brand/primary-strong-perma",
   "binding": "brand/1/l-constant/12",
   "description": "🔒 LOCKED · text/ v2.3.2 — First brand colour, emphasis register, light-world reading pinned — the deep identity that never flips.",
   "L": "#19394d",
   "D": "#061016"
  },
  {
   "name": "text/brand/secondary-subtle",
   "binding": "brand/2/10",
   "description": "🔒 LOCKED · text/ v2.3.2 — Second brand colour, decorative register — below body-text contrast.",
   "L": "#81b228",
   "D": "#81b321"
  },
  {
   "name": "text/brand/secondary-inverse",
   "binding": "brand/2/inverse/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — Second brand colour, opposite of theme.",
   "L": "#98cb46",
   "D": "#517700"
  },
  {
   "name": "text/brand/secondary-strong-perma",
   "binding": "brand/2/l-constant/12",
   "description": "🔒 LOCKED · text/ v2.3.2 — Second brand colour, emphasis register, light-world reading pinned.",
   "L": "#304215",
   "D": "#0c1008"
  },
  {
   "name": "text/brand/tertiary-subtle",
   "binding": "brand/3/10",
   "description": "🔒 LOCKED · text/ v2.3.2 — Third brand colour, decorative register — below body-text contrast.",
   "L": "#5a24ad",
   "D": "#5a24ad"
  },
  {
   "name": "text/brand/tertiary-inverse",
   "binding": "brand/3/inverse/11",
   "description": "🔒 LOCKED · text/ v2.3.2 — Third brand colour, opposite of theme.",
   "L": "#bda2ff",
   "D": "#6940b9"
  },
  {
   "name": "text/brand/tertiary-strong-perma",
   "binding": "brand/3/l-constant/12",
   "description": "🔒 LOCKED · text/ v2.3.2 — Third brand colour, emphasis register, light-world reading pinned.",
   "L": "#372163",
   "D": "#0f0c19"
  },
  {
   "name": "fg/primary",
   "binding": "brand/black",
   "description": "🔒 LOCKED · fg/ v2.3.2 — The default glyph voice — icon strokes, indicator dots, tick lines.",
   "L": "#071013",
   "D": "#fafafa"
  },
  {
   "name": "fg/primary/inverse-perma",
   "binding": "brand/white/l-constant",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Glyph paper voice, dark-world reading pinned — chrome capsules, the constant button.",
   "L": "#fafafa",
   "D": "#fafafa"
  },
  {
   "name": "fg/primary/subtle",
   "binding": "neutral/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Supporting glyph register.",
   "L": "#60646c",
   "D": "#b0b4ba"
  },
  {
   "name": "fg/primary/muted",
   "binding": "neutral/10",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Muted glyph register — inactive but present; the quietest readable glyph tier.",
   "L": "#80838d",
   "D": "#777b84"
  },
  {
   "name": "fg/primary/inverse",
   "binding": "brand/white",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Glyphs on surfaces that invert against the theme.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "fg/primary/perma",
   "binding": "brand/black/l-constant",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Glyph ink voice, light-world reading pinned — constant-light surfaces.",
   "L": "#071013",
   "D": "#071013"
  },
  {
   "name": "fg/primary/subtle-inverse",
   "binding": "brand/white/alpha/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Supporting glyph register, opposite of theme — quiet marks on inverse surfaces.",
   "L": "#fafafab2",
   "D": "#071013b2"
  },
  {
   "name": "fg/primary/subtle-perma",
   "binding": "brand/black/l-alpha/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Supporting glyph register, light-world reading pinned.",
   "L": "#071013b2",
   "D": "#071013b2"
  },
  {
   "name": "fg/primary/subtle-inverse-perma",
   "binding": "brand/white/l-alpha/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Supporting glyph register, dark-world reading pinned — quiet marks on chrome.",
   "L": "#fafafab2",
   "D": "#fafafab2"
  },
  {
   "name": "fg/max",
   "binding": "base/black",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Maximum contrast, follows theme. Media absolutes only — UI glyphs use primary.",
   "L": "#000000",
   "D": "#ffffff"
  },
  {
   "name": "fg/max/inverse-perma",
   "binding": "base/white/l-constant",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Glyph light extreme pinned — imagery; luminance-picked with max-perma.",
   "L": "#ffffff",
   "D": "#ffffff"
  },
  {
   "name": "fg/max/perma",
   "binding": "base/black/l-constant",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Glyph dark extreme pinned — light imagery.",
   "L": "#000000",
   "D": "#000000"
  },
  {
   "name": "fg/max/inverse",
   "binding": "base/white",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Maximum contrast, opposite of theme.",
   "L": "#ffffff",
   "D": "#000000"
  },
  {
   "name": "fg/system/disabled",
   "binding": "neutral/8",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Unavailable control glyphs.",
   "L": "#b9bbc6",
   "D": "#5a6169"
  },
  {
   "name": "fg/system/disabled-subtle",
   "binding": "neutral/7",
   "description": "🔒 LOCKED · fg/ v2.3.2 — The quieter disabled glyph tier.",
   "L": "#cdced6",
   "D": "#43484e"
  },
  {
   "name": "fg/system/error",
   "binding": "error/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Status glyph voice.",
   "L": "#bc3438",
   "D": "#ff8f89"
  },
  {
   "name": "fg/system/error-solid",
   "binding": "error/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Status solid voice — graphic accents.",
   "L": "#bf373a",
   "D": "#bf373a"
  },
  {
   "name": "fg/system/warning",
   "binding": "warning/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Status glyph voice.",
   "L": "#7b7600",
   "D": "#e4df4d"
  },
  {
   "name": "fg/system/warning-solid",
   "binding": "warning/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Status solid voice — graphic accents.",
   "L": "#d8d33e",
   "D": "#d8d33e"
  },
  {
   "name": "fg/system/success",
   "binding": "success/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Status glyph voice.",
   "L": "#007d1c",
   "D": "#57d574"
  },
  {
   "name": "fg/system/success-solid",
   "binding": "success/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Status solid voice — graphic accents.",
   "L": "#37bf5d",
   "D": "#37bf5d"
  },
  {
   "name": "fg/brand/primary",
   "binding": "brand/1/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — First brand colour as glyph — active/accent glyphs.",
   "L": "#1170a1",
   "D": "#73c4f8"
  },
  {
   "name": "fg/brand/primary-solid",
   "binding": "brand/1/9",
   "description": "🔒 LOCKED · fg/ v2.3.2 — First brand colour, solid voice — graphic accents: the dial arc, gauges, badges.",
   "L": "#378cbe",
   "D": "#378cbe"
  },
  {
   "name": "fg/brand/primary-subtle",
   "binding": "brand/1/10",
   "description": "🔒 LOCKED · fg/ v2.3.2 — First brand colour, decorative register — below the glyph-contrast floor for small marks; ornament only.",
   "L": "#287fb0",
   "D": "#287fb0"
  },
  {
   "name": "fg/brand/primary-strong",
   "binding": "brand/1/12",
   "description": "🔒 LOCKED · fg/ v2.3.2 — First brand colour, emphasis register.",
   "L": "#19394d",
   "D": "#c4ecff"
  },
  {
   "name": "fg/brand/primary-inverse",
   "binding": "brand/1/inverse/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — First brand colour, opposite of theme.",
   "L": "#73c4f8",
   "D": "#1170a1"
  },
  {
   "name": "fg/brand/primary-strong-perma",
   "binding": "brand/1/l-constant/12",
   "description": "🔒 LOCKED · fg/ v2.3.2 — First brand colour, emphasis register, light-world reading pinned.",
   "L": "#19394d",
   "D": "#061016"
  },
  {
   "name": "fg/brand/secondary",
   "binding": "brand/2/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Second brand colour as glyph.",
   "L": "#517700",
   "D": "#98cb46"
  },
  {
   "name": "fg/brand/secondary-subtle",
   "binding": "brand/2/10",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Second brand colour, decorative register.",
   "L": "#81b228",
   "D": "#81b321"
  },
  {
   "name": "fg/brand/secondary-inverse",
   "binding": "brand/2/inverse/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Second brand colour, opposite of theme.",
   "L": "#98cb46",
   "D": "#517700"
  },
  {
   "name": "fg/brand/secondary-strong-perma",
   "binding": "brand/2/l-constant/12",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Second brand colour, emphasis register, light-world reading pinned.",
   "L": "#304215",
   "D": "#0c1008"
  },
  {
   "name": "fg/brand/tertiary",
   "binding": "brand/3/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Third brand colour as glyph.",
   "L": "#6940b9",
   "D": "#bda2ff"
  },
  {
   "name": "fg/brand/tertiary-subtle",
   "binding": "brand/3/10",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Third brand colour, decorative register.",
   "L": "#5a24ad",
   "D": "#5a24ad"
  },
  {
   "name": "fg/brand/tertiary-inverse",
   "binding": "brand/3/inverse/11",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Third brand colour, opposite of theme.",
   "L": "#bda2ff",
   "D": "#6940b9"
  },
  {
   "name": "fg/brand/tertiary-strong-perma",
   "binding": "brand/3/l-constant/12",
   "description": "🔒 LOCKED · fg/ v2.3.2 — Third brand colour, emphasis register, light-world reading pinned.",
   "L": "#372163",
   "D": "#0f0c19"
  },
  {
   "name": "border/primary",
   "binding": "neutral/7",
   "description": "Primary border. Use for input fields and card edges.",
   "L": "#cdced6",
   "D": "#43484e"
  },
  {
   "name": "border/secondary",
   "binding": "neutral/6",
   "description": "Secondary border. Subtler than primary.",
   "L": "#d9d9e0",
   "D": "#363a3f"
  },
  {
   "name": "border/secondary-alt",
   "binding": "neutral/5",
   "description": "Alternative secondary border.",
   "L": "#e0e1e6",
   "D": "#2e3135"
  },
  {
   "name": "border/tertiary",
   "binding": "neutral/5",
   "description": "Tertiary border. Subtle dividers.",
   "L": "#e0e1e6",
   "D": "#2e3135"
  },
  {
   "name": "border/disabled",
   "binding": "neutral/6",
   "description": "Disabled border.",
   "L": "#d9d9e0",
   "D": "#363a3f"
  },
  {
   "name": "border/disabled-subtle",
   "binding": "neutral/5",
   "description": "Subtle disabled border. Lower contrast.",
   "L": "#e0e1e6",
   "D": "#2e3135"
  },
  {
   "name": "border/brand",
   "binding": "brand/1/8",
   "description": "Brand-coloured border.",
   "L": "#60a8d7",
   "D": "#237cad"
  },
  {
   "name": "border/brand-alt",
   "binding": "brand/1/7",
   "description": "Alternative brand-coloured border.",
   "L": "#8cbfe2",
   "D": "#1e658d"
  },
  {
   "name": "border/error",
   "binding": "error/8",
   "description": "Error state border.",
   "L": "#dc8d87",
   "D": "#c0383b"
  },
  {
   "name": "border/error-subtle",
   "binding": "error/7",
   "description": "Subtle error border. Lower contrast.",
   "L": "#e6a6a1",
   "D": "#942a2c"
  },
  {
   "name": "bg/overlay",
   "binding": "alpha/base/brand-white/2",
   "description": "Overlay background for modals and scrims. Immutable — stays dark in all themes.",
   "L": "#fafafa1a",
   "D": "#0710131a"
  },
  {
   "name": "bg/active",
   "binding": "base/white",
   "description": "Active/pressed state background.",
   "L": "#ffffff",
   "D": "#000000"
  },
  {
   "name": "bg/disabled",
   "binding": "neutral/3",
   "description": "Disabled state background. Reduced contrast.",
   "L": "#f0f0f3",
   "D": "#212225"
  },
  {
   "name": "bg/primary",
   "binding": "brand/white",
   "description": "Primary background surface. Use for page backgrounds and main content areas.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "bg/primary-solid",
   "binding": "brand/black/l-constant",
   "description": "Solid dark background. Immutable — stays dark in all themes.",
   "L": "#071013",
   "D": "#071013"
  },
  {
   "name": "bg/primary-semi-solid",
   "binding": "neutral/l-constant/11",
   "description": "Overlay background for modals and scrims. Immutable — stays dark in all themes.",
   "L": "#60646c",
   "D": "#18191b"
  },
  {
   "name": "bg/primary-solid-lighter",
   "binding": "neutral/l-constant/11",
   "description": "Overlay background for modals and scrims. Immutable — stays dark in all themes.",
   "L": "#60646c",
   "D": "#18191b"
  },
  {
   "name": "bg/primary-alt",
   "binding": "brand/white",
   "description": "Alternative primary background. Use for subtle differentiation from bg-primary.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "bg/primary-alt-trans",
   "binding": "alpha/base/brand-white/11",
   "description": "Alternative primary background. Use for subtle differentiation from bg-primary.",
   "L": "#fafafae5",
   "D": "#071013e5"
  },
  {
   "name": "bg/primary-hover",
   "binding": "neutral/2",
   "description": "Hover state for primary background.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/secondary",
   "binding": "neutral/2",
   "description": "Secondary background. Use for cards, panels, and elevated surfaces.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/secondary-alt",
   "binding": "neutral/2",
   "description": "Alternative secondary background.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/secondary-hover",
   "binding": "neutral/3",
   "description": "Hover state for secondary backgrounds.",
   "L": "#f0f0f3",
   "D": "#212225"
  },
  {
   "name": "bg/secondary-subtle",
   "binding": "brand/white",
   "description": "Subtle secondary background. Lighter than bg-secondary.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "bg/secondary-solid",
   "binding": "neutral/9",
   "description": "Solid secondary background.",
   "L": "#8b8d98",
   "D": "#696e77"
  },
  {
   "name": "bg/tertiary",
   "binding": "neutral/3",
   "description": "Tertiary background. Use for nested containers and inset areas.",
   "L": "#f0f0f3",
   "D": "#212225"
  },
  {
   "name": "bg/quaternary",
   "binding": "neutral/4",
   "description": "Quaternary background. Deepest nesting level.",
   "L": "#e8e8ec",
   "D": "#272a2d"
  },
  {
   "name": "bg/disabled-subtle",
   "binding": "neutral/2",
   "description": "Subtle disabled background.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/brand-primary",
   "binding": "brand/1/2",
   "description": "Brand accent background. Subtle tint.",
   "L": "#eef4f8",
   "D": "#0e1a22"
  },
  {
   "name": "bg/brand-primary-alt",
   "binding": "brand/1/2",
   "description": "Alternative brand accent background.",
   "L": "#eef4f8",
   "D": "#0e1a22"
  },
  {
   "name": "bg/brand-secondary",
   "binding": "brand/1/3",
   "description": "Brand accent secondary background.",
   "L": "#deeef9",
   "D": "#0a293c"
  },
  {
   "name": "bg/brand-solid",
   "binding": "brand/1/9",
   "description": "Solid brand background. Use for primary CTAs and brand moments.",
   "L": "#378cbe",
   "D": "#378cbe"
  },
  {
   "name": "bg/brand-solid-hover",
   "binding": "brand/1/10",
   "description": "Hover state for solid brand background.",
   "L": "#287fb0",
   "D": "#287fb0"
  },
  {
   "name": "bg/brand-section",
   "binding": "brand/1/9",
   "description": "Brand section background. Large area brand tint.",
   "L": "#378cbe",
   "D": "#378cbe"
  },
  {
   "name": "bg/brand-section-subtle",
   "binding": "brand/1/3",
   "description": "Subtle brand section background.",
   "L": "#deeef9",
   "D": "#0a293c"
  },
  {
   "name": "bg/error-primary",
   "binding": "error/2",
   "description": "Error state primary background.",
   "L": "#f9f2f1",
   "D": "#211211"
  },
  {
   "name": "bg/error-secondary",
   "binding": "error/3",
   "description": "Error state secondary background.",
   "L": "#f7e6e4",
   "D": "#3e0e0e"
  },
  {
   "name": "bg/error-solid",
   "binding": "error/9",
   "description": "Solid error background. High contrast for alerts.",
   "L": "#bf373a",
   "D": "#bf373a"
  },
  {
   "name": "bg/error-solid-hover",
   "binding": "error/10",
   "description": "Hover state for solid error background.",
   "L": "#af262d",
   "D": "#a33838"
  },
  {
   "name": "bg/warning-primary",
   "binding": "warning/2",
   "description": "Warning state primary background.",
   "L": "#f7f7e0",
   "D": "#18180e"
  },
  {
   "name": "bg/warning-secondary",
   "binding": "warning/3",
   "description": "Warning state secondary background.",
   "L": "#f7f6a4",
   "D": "#262610"
  },
  {
   "name": "bg/warning-solid",
   "binding": "warning/9",
   "description": "Solid warning background.",
   "L": "#d8d33e",
   "D": "#d8d33e"
  },
  {
   "name": "bg/success-primary",
   "binding": "success/2",
   "description": "Success state primary background.",
   "L": "#eef6ef",
   "D": "#121a13"
  },
  {
   "name": "bg/success-secondary",
   "binding": "success/3",
   "description": "Success state secondary background.",
   "L": "#def2e0",
   "D": "#182a1b"
  },
  {
   "name": "bg/success-solid",
   "binding": "success/9",
   "description": "Solid success background.",
   "L": "#37bf5d",
   "D": "#37bf5d"
  }
 ]
} as const;
