// GENERATED by pull-ds-tokens.mjs — do not edit. Source: the Figma file.
export const RESOLVED = {
 "fileKey": "Qdb9Kx98afJHxaCGAIxoMC",
 "pulledAtFileVersion": null,
 "tokens": [
  {
   "name": "text/primary",
   "binding": "brand/black",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Primary text colour. Use for headings and body copy.",
   "L": "#071013",
   "D": "#fafafa"
  },
  {
   "name": "text/primary-subtle",
   "binding": "neutral/11",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Secondary text. Slightly muted for supporting content.",
   "L": "#60646c",
   "D": "#b0b4ba"
  },
  {
   "name": "text/disabled",
   "binding": "neutral/8",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Disabled text. Low contrast.",
   "L": "#b9bbc6",
   "D": "#5a6169"
  },
  {
   "name": "text/placeholder",
   "binding": "neutral/9",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Placeholder text in inputs.",
   "L": "#8b8d98",
   "D": "#696e77"
  },
  {
   "name": "text/brand-primary",
   "binding": "brand/1/11",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Brand-coloured text. Use sparingly for emphasis.",
   "L": "#1170a1",
   "D": "#73c4f8"
  },
  {
   "name": "text/brand-secondary",
   "binding": "brand/2/11",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Lime-moss text. NOTE: name reused — the old brand-secondary (blue dupe) died into brand-primary.",
   "L": "#517700",
   "D": "#98cb46"
  },
  {
   "name": "text/brand-tertiary",
   "binding": "brand/3/11",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Indigo-bloom text. NOTE: name reused — the old brand-tertiary (blue dupe) died into brand-primary.",
   "L": "#6940b9",
   "D": "#bda2ff"
  },
  {
   "name": "text/error",
   "binding": "error/12",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Error text. Use for validation messages.",
   "L": "#601f1e",
   "D": "#ffcfcb"
  },
  {
   "name": "text/warning",
   "binding": "warning/12",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Warning text.",
   "L": "#403f19",
   "D": "#f2f1b3"
  },
  {
   "name": "text/success",
   "binding": "success/11",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Success text.",
   "L": "#007d1c",
   "D": "#57d574"
  },
  {
   "name": "text/max",
   "binding": "base/black",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — True maximum contrast, follows theme. Absolutes only — UI text uses primary.",
   "L": "#000000",
   "D": "#ffffff"
  },
  {
   "name": "text/max-inverse",
   "binding": "base/white",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — White in light theme, black in dark — text on surfaces that invert against the theme.",
   "L": "#ffffff",
   "D": "#000000"
  },
  {
   "name": "text/max-dark",
   "binding": "base/black/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Pure black pinned, never flips — text over light imagery (luminance-picked with max-light).",
   "L": "#000000",
   "D": "#000000"
  },
  {
   "name": "text/max-light",
   "binding": "base/white/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Pure white pinned, never flips — photo text. Pairs with scrim/on-image or region-luminance pick.",
   "L": "#ffffff",
   "D": "#ffffff"
  },
  {
   "name": "text/primary-inverse",
   "binding": "brand/white",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Paper in light, ink in dark — the flipping black button.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "text/primary-dark",
   "binding": "brand/black/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Ink voice pinned, never flips — text on constant-light surfaces.",
   "L": "#071013",
   "D": "#071013"
  },
  {
   "name": "text/primary-light",
   "binding": "brand/white/l-constant",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — Paper voice pinned, never flips — the constant-black button, ink panel, chrome capsules.",
   "L": "#fafafa",
   "D": "#fafafa"
  },
  {
   "name": "text/primary-subtle-inverse",
   "binding": "brand/white/alpha/9",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — 70% paper → 70% ink — supporting text on the flipping black button.",
   "L": "#fafafab2",
   "D": "#071013b2"
  },
  {
   "name": "text/primary-subtle-dark",
   "binding": "brand/black/l-alpha/9",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — 70% ink pinned — supporting text on constant-light surfaces.",
   "L": "#071013b2",
   "D": "#071013b2"
  },
  {
   "name": "text/primary-subtle-light",
   "binding": "brand/white/l-alpha/9",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — 70% paper pinned — supporting text on the constant-black button, chrome.",
   "L": "#fafafab2",
   "D": "#fafafab2"
  },
  {
   "name": "text/brand-primary-strong",
   "binding": "brand/1/12",
   "description": "🔒 LOCKED · text/ v2.3.2 · 2026-07-11 — High emphasis + the text on brand-primary tints (on-colour law: tint carries own 12).",
   "L": "#19394d",
   "D": "#c4ecff"
  },
  {
   "name": "border/primary",
   "binding": "neutral/7",
   "description": "Primary border. Use for input fields and card edges.",
   "L": "#cdced6",
   "D": "#43484e"
  },
  {
   "name": "border/secondary",
   "binding": "neutral/6",
   "description": "Secondary border. Subtler than primary.",
   "L": "#d9d9e0",
   "D": "#363a3f"
  },
  {
   "name": "border/secondary-alt",
   "binding": "neutral/5",
   "description": "Alternative secondary border.",
   "L": "#e0e1e6",
   "D": "#2e3135"
  },
  {
   "name": "border/tertiary",
   "binding": "neutral/5",
   "description": "Tertiary border. Subtle dividers.",
   "L": "#e0e1e6",
   "D": "#2e3135"
  },
  {
   "name": "border/disabled",
   "binding": "neutral/6",
   "description": "Disabled border.",
   "L": "#d9d9e0",
   "D": "#363a3f"
  },
  {
   "name": "border/disabled-subtle",
   "binding": "neutral/5",
   "description": "Subtle disabled border. Lower contrast.",
   "L": "#e0e1e6",
   "D": "#2e3135"
  },
  {
   "name": "border/brand",
   "binding": "brand/1/8",
   "description": "Brand-coloured border.",
   "L": "#60a8d7",
   "D": "#237cad"
  },
  {
   "name": "border/brand-alt",
   "binding": "brand/1/7",
   "description": "Alternative brand-coloured border.",
   "L": "#8cbfe2",
   "D": "#1e658d"
  },
  {
   "name": "border/error",
   "binding": "error/8",
   "description": "Error state border.",
   "L": "#dc8d87",
   "D": "#c0383b"
  },
  {
   "name": "border/error-subtle",
   "binding": "error/7",
   "description": "Subtle error border. Lower contrast.",
   "L": "#e6a6a1",
   "D": "#942a2c"
  },
  {
   "name": "fg/white",
   "binding": "base/white",
   "description": "White foreground. Icons on dark/solid backgrounds. Always #FFF.",
   "L": "#ffffff",
   "D": "#000000"
  },
  {
   "name": "fg/solid-white",
   "binding": "l-constant/base/white",
   "description": "White foreground. Icons on dark/solid backgrounds. Always #FFF.",
   "L": "#ffffff",
   "D": "#ffffff"
  },
  {
   "name": "fg/solid-light-grey",
   "binding": "l-constant/grey/1",
   "description": "White foreground. Icons on dark/solid backgrounds. Always #FFF.",
   "L": "#fcfcfd",
   "D": "#edeef0"
  },
  {
   "name": "fg/solid-off-white-",
   "binding": "l-constant/grey/2",
   "description": "White foreground. Icons on dark/solid backgrounds. Always #FFF.",
   "L": "#f9f9fb",
   "D": "#b0b4ba"
  },
  {
   "name": "fg/primary",
   "binding": "brand/black",
   "description": "Primary foreground. Icons and decorative elements.",
   "L": "#071013",
   "D": "#fafafa"
  },
  {
   "name": "fg/secondary",
   "binding": "neutral/11",
   "description": "Secondary foreground. Supporting icons.",
   "L": "#60646c",
   "D": "#b0b4ba"
  },
  {
   "name": "fg/secondary-hover",
   "binding": "brand/black",
   "description": "Hover state for secondary foreground.",
   "L": "#071013",
   "D": "#fafafa"
  },
  {
   "name": "fg/tertiary",
   "binding": "neutral/11",
   "description": "Tertiary foreground. Muted icons.",
   "L": "#60646c",
   "D": "#b0b4ba"
  },
  {
   "name": "fg/tertiary-hover",
   "binding": "brand/black",
   "description": "Hover state for tertiary foreground.",
   "L": "#071013",
   "D": "#fafafa"
  },
  {
   "name": "fg/quaternary",
   "binding": "neutral/10",
   "description": "Quaternary foreground. Least prominent icons.",
   "L": "#80838d",
   "D": "#777b84"
  },
  {
   "name": "fg/quaternary-hover",
   "binding": "neutral/11",
   "description": "Hover state for quaternary foreground.",
   "L": "#60646c",
   "D": "#b0b4ba"
  },
  {
   "name": "fg/disabled",
   "binding": "neutral/8",
   "description": "Disabled foreground.",
   "L": "#b9bbc6",
   "D": "#5a6169"
  },
  {
   "name": "fg/disabled-subtle",
   "binding": "neutral/7",
   "description": "Subtle disabled foreground. Lower contrast.",
   "L": "#cdced6",
   "D": "#43484e"
  },
  {
   "name": "fg/brand-primary",
   "binding": "brand/1/11",
   "description": "Brand-coloured foreground/icons.",
   "L": "#1170a1",
   "D": "#73c4f8"
  },
  {
   "name": "fg/brand-primary-alt",
   "binding": "brand/1/11",
   "description": "Alternative brand-coloured foreground.",
   "L": "#1170a1",
   "D": "#73c4f8"
  },
  {
   "name": "fg/brand-secondary",
   "binding": "brand/1/9",
   "description": "Secondary brand foreground/icons.",
   "L": "#378cbe",
   "D": "#378cbe"
  },
  {
   "name": "fg/brand-secondary-alt",
   "binding": "brand/1/10",
   "description": "Alternative secondary brand foreground.",
   "L": "#287fb0",
   "D": "#287fb0"
  },
  {
   "name": "fg/brand-secondary-hover",
   "binding": "brand/1/10",
   "description": "Hover state for secondary brand foreground.",
   "L": "#287fb0",
   "D": "#287fb0"
  },
  {
   "name": "fg/error-primary",
   "binding": "error/11",
   "description": "Error foreground/icon.",
   "L": "#bc3438",
   "D": "#ff8f89"
  },
  {
   "name": "fg/error-secondary",
   "binding": "error/9",
   "description": "Secondary error foreground.",
   "L": "#bf373a",
   "D": "#bf373a"
  },
  {
   "name": "fg/warning-primary",
   "binding": "warning/11",
   "description": "Warning foreground/icon.",
   "L": "#7b7600",
   "D": "#e4df4d"
  },
  {
   "name": "fg/warning-secondary",
   "binding": "warning/9",
   "description": "Secondary warning foreground.",
   "L": "#d8d33e",
   "D": "#d8d33e"
  },
  {
   "name": "fg/success-primary",
   "binding": "success/11",
   "description": "Success foreground/icon.",
   "L": "#007d1c",
   "D": "#57d574"
  },
  {
   "name": "fg/success-secondary",
   "binding": "success/9",
   "description": "Secondary success foreground.",
   "L": "#37bf5d",
   "D": "#37bf5d"
  },
  {
   "name": "bg/overlay",
   "binding": "alpha/base/brand-white/2",
   "description": "Overlay background for modals and scrims. Immutable — stays dark in all themes.",
   "L": "#fafafa1a",
   "D": "#0710131a"
  },
  {
   "name": "bg/active",
   "binding": "base/white",
   "description": "Active/pressed state background.",
   "L": "#ffffff",
   "D": "#000000"
  },
  {
   "name": "bg/disabled",
   "binding": "neutral/3",
   "description": "Disabled state background. Reduced contrast.",
   "L": "#f0f0f3",
   "D": "#212225"
  },
  {
   "name": "bg/primary",
   "binding": "brand/white",
   "description": "Primary background surface. Use for page backgrounds and main content areas.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "bg/primary-solid",
   "binding": "brand/black/l-constant",
   "description": "Solid dark background. Immutable — stays dark in all themes.",
   "L": "#071013",
   "D": "#071013"
  },
  {
   "name": "bg/primary-semi-solid",
   "binding": "neutral/l-constant/11",
   "description": "Overlay background for modals and scrims. Immutable — stays dark in all themes.",
   "L": "#60646c",
   "D": "#18191b"
  },
  {
   "name": "bg/primary-solid-lighter",
   "binding": "neutral/l-constant/11",
   "description": "Overlay background for modals and scrims. Immutable — stays dark in all themes.",
   "L": "#60646c",
   "D": "#18191b"
  },
  {
   "name": "bg/primary-alt",
   "binding": "brand/white",
   "description": "Alternative primary background. Use for subtle differentiation from bg-primary.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "bg/primary-alt-trans",
   "binding": "alpha/base/brand-white/11",
   "description": "Alternative primary background. Use for subtle differentiation from bg-primary.",
   "L": "#fafafae5",
   "D": "#071013e5"
  },
  {
   "name": "bg/primary-hover",
   "binding": "neutral/2",
   "description": "Hover state for primary background.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/secondary",
   "binding": "neutral/2",
   "description": "Secondary background. Use for cards, panels, and elevated surfaces.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/secondary-alt",
   "binding": "neutral/2",
   "description": "Alternative secondary background.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/secondary-hover",
   "binding": "neutral/3",
   "description": "Hover state for secondary backgrounds.",
   "L": "#f0f0f3",
   "D": "#212225"
  },
  {
   "name": "bg/secondary-subtle",
   "binding": "brand/white",
   "description": "Subtle secondary background. Lighter than bg-secondary.",
   "L": "#fafafa",
   "D": "#071013"
  },
  {
   "name": "bg/secondary-solid",
   "binding": "neutral/9",
   "description": "Solid secondary background.",
   "L": "#8b8d98",
   "D": "#696e77"
  },
  {
   "name": "bg/tertiary",
   "binding": "neutral/3",
   "description": "Tertiary background. Use for nested containers and inset areas.",
   "L": "#f0f0f3",
   "D": "#212225"
  },
  {
   "name": "bg/quaternary",
   "binding": "neutral/4",
   "description": "Quaternary background. Deepest nesting level.",
   "L": "#e8e8ec",
   "D": "#272a2d"
  },
  {
   "name": "bg/disabled-subtle",
   "binding": "neutral/2",
   "description": "Subtle disabled background.",
   "L": "#f9f9fb",
   "D": "#18191b"
  },
  {
   "name": "bg/brand-primary",
   "binding": "brand/1/2",
   "description": "Brand accent background. Subtle tint.",
   "L": "#eef4f8",
   "D": "#0e1a22"
  },
  {
   "name": "bg/brand-primary-alt",
   "binding": "brand/1/2",
   "description": "Alternative brand accent background.",
   "L": "#eef4f8",
   "D": "#0e1a22"
  },
  {
   "name": "bg/brand-secondary",
   "binding": "brand/1/3",
   "description": "Brand accent secondary background.",
   "L": "#deeef9",
   "D": "#0a293c"
  },
  {
   "name": "bg/brand-solid",
   "binding": "brand/1/9",
   "description": "Solid brand background. Use for primary CTAs and brand moments.",
   "L": "#378cbe",
   "D": "#378cbe"
  },
  {
   "name": "bg/brand-solid-hover",
   "binding": "brand/1/10",
   "description": "Hover state for solid brand background.",
   "L": "#287fb0",
   "D": "#287fb0"
  },
  {
   "name": "bg/brand-section",
   "binding": "brand/1/9",
   "description": "Brand section background. Large area brand tint.",
   "L": "#378cbe",
   "D": "#378cbe"
  },
  {
   "name": "bg/brand-section-subtle",
   "binding": "brand/1/3",
   "description": "Subtle brand section background.",
   "L": "#deeef9",
   "D": "#0a293c"
  },
  {
   "name": "bg/error-primary",
   "binding": "error/2",
   "description": "Error state primary background.",
   "L": "#f9f2f1",
   "D": "#211211"
  },
  {
   "name": "bg/error-secondary",
   "binding": "error/3",
   "description": "Error state secondary background.",
   "L": "#f7e6e4",
   "D": "#3e0e0e"
  },
  {
   "name": "bg/error-solid",
   "binding": "error/9",
   "description": "Solid error background. High contrast for alerts.",
   "L": "#bf373a",
   "D": "#bf373a"
  },
  {
   "name": "bg/error-solid-hover",
   "binding": "error/10",
   "description": "Hover state for solid error background.",
   "L": "#af262d",
   "D": "#a33838"
  },
  {
   "name": "bg/warning-primary",
   "binding": "warning/2",
   "description": "Warning state primary background.",
   "L": "#f7f7e0",
   "D": "#18180e"
  },
  {
   "name": "bg/warning-secondary",
   "binding": "warning/3",
   "description": "Warning state secondary background.",
   "L": "#f7f6a4",
   "D": "#262610"
  },
  {
   "name": "bg/warning-solid",
   "binding": "warning/9",
   "description": "Solid warning background.",
   "L": "#d8d33e",
   "D": "#d8d33e"
  },
  {
   "name": "bg/success-primary",
   "binding": "success/2",
   "description": "Success state primary background.",
   "L": "#eef6ef",
   "D": "#121a13"
  },
  {
   "name": "bg/success-secondary",
   "binding": "success/3",
   "description": "Success state secondary background.",
   "L": "#def2e0",
   "D": "#182a1b"
  },
  {
   "name": "bg/success-solid",
   "binding": "success/9",
   "description": "Solid success background.",
   "L": "#37bf5d",
   "D": "#37bf5d"
  }
 ]
} as const;
