// Generated by figma-to-code — deterministic, do not hand-edit structure (edit via react-figma).
import styles from './mother-v2.module.css';

export default function MotherV2() {
  return (
    <div className={styles.motherV2} data-fc="4311:31631">
      <div className={styles.topSection} data-fc="4311:31632">
        <div className={styles.titleAndControls} data-fc="4311:31633">
          <div className={styles.buttonGroupLeading} data-fc="4311:31634">
            <svg className={styles.icon} data-fc="4311:31638" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31638)">
<path d="M15.625 4.375L4.375 15.625" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M15.625 15.625L4.375 4.375" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31638">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

          </div>
          <h4 className={styles.effect} data-fc="4311:31642">Effect</h4>
          <div className={styles.buttonGroupLeading2} data-fc="4311:31863">
            <svg className={styles.icon2} data-fc="4311:31868" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M2.8125 10.625L7.1875 15L17.1875 5" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>
</svg>

          </div>
        </div>
      </div>
      <div className={styles.canvas} data-fc="4311:31651">
        <div className={styles.rectangle49} data-fc="4311:31652" />
      </div>
      <div className={styles.bottomSection} data-fc="4311:31653">
        <div className={styles.toolbox} data-fc="4311:31654">
          <div className={styles.tool} data-fc="4311:31655">
            <div className={styles.dial} data-fc="4311:31656">
              <svg className={styles.icon3} data-fc="4311:31657" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31657)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5286 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23753 11.8789C3.4715 10.6143 4.05497 9.44054 4.92183 8.49056C5.78869 7.54058 6.90428 6.85237 8.14222 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31657">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial2} data-fc="4311:31666">
              <svg className={styles.icon4} data-fc="4311:31667" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31667)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5286 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23753 11.8789C3.4715 10.6143 4.05497 9.44054 4.92183 8.49056C5.78869 7.54058 6.90428 6.85237 8.14222 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31667">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial3} data-fc="4311:31676">
              <svg className={styles.icon5} data-fc="4311:31677" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31677)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5286 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23753 11.8789C3.4715 10.6143 4.05497 9.44054 4.92183 8.49056C5.78869 7.54058 6.90428 6.85237 8.14222 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31677">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial4} data-fc="4311:31686">
              <svg className={styles.icon6} data-fc="4311:31687" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31687)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5286 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23753 11.8789C3.4715 10.6143 4.05497 9.44054 4.92183 8.49056C5.78869 7.54058 6.90428 6.85237 8.14222 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31687">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial5} data-fc="4311:31696">
              <svg className={styles.icon7} data-fc="4311:31697" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31697)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5286 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23753 11.8789C3.4715 10.6143 4.05497 9.44054 4.92183 8.49056C5.78869 7.54058 6.90428 6.85237 8.14222 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31697">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial6} data-fc="4311:31706">
              <svg className={styles.icon8} data-fc="4311:31707" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31707)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5286 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23753 11.8789C3.4715 10.6143 4.05497 9.44054 4.92183 8.49056C5.78869 7.54058 6.90428 6.85237 8.14222 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31707">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial7} data-fc="4311:31716">
              <svg className={styles.icon9} data-fc="4311:31717" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31717)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5287 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23755 11.8789C3.47152 10.6143 4.05498 9.44054 4.92184 8.49056C5.7887 7.54058 6.9043 6.85237 8.14224 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31717">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial8} data-fc="4311:31726">
              <svg className={styles.icon10} data-fc="4311:31727" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31727)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5287 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23755 11.8789C3.47152 10.6143 4.05498 9.44054 4.92184 8.49056C5.7887 7.54058 6.9043 6.85237 8.14224 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31727">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
            <div className={styles.dial9} data-fc="4311:31736">
              <svg className={styles.icon11} data-fc="4311:31737" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4311_31737)">
<path d="M1.25 6.25H8.125" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.875 6.25H18.75" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M10 8.125C11.0355 8.125 11.875 7.28553 11.875 6.25C11.875 5.21447 11.0355 4.375 10 4.375C8.96447 4.375 8.125 5.21447 8.125 6.25C8.125 7.28553 8.96447 8.125 10 8.125Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.125 15.625C4.16053 15.625 5 14.7855 5 13.75C5 12.7145 4.16053 11.875 3.125 11.875C2.08947 11.875 1.25 12.7145 1.25 13.75C1.25 14.7855 2.08947 15.625 3.125 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M16.875 15.625C17.9105 15.625 18.75 14.7855 18.75 13.75C18.75 12.7145 17.9105 11.875 16.875 11.875C15.8395 11.875 15 12.7145 15 13.75C15 14.7855 15.8395 15.625 16.875 15.625Z" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M11.8578 6.50391C13.0958 6.85228 14.2115 7.54047 15.0783 8.49047C15.9452 9.44046 16.5287 10.6143 16.7625 11.8789" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
<path d="M3.23755 11.8789C3.47152 10.6143 4.05498 9.44054 4.92184 8.49056C5.7887 7.54058 6.9043 6.85237 8.14224 6.50391" stroke="currentColor" strokeWidth="0.9375" strokeLinecap="round" strokeLinejoin="round"/>
</g>
<defs>
<clipPath id="clip0_4311_31737">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>

            </div>
          </div>
          <div className={styles.tool2} data-fc="4311:31746">
            <div className={styles.ruller} data-fc="4311:31747">
              <div className={styles.tick} data-fc="4311:31748" />
              <div className={styles.line58} data-fc="4311:31749" />
              <div className={styles.line80} data-fc="4311:31750" />
              <div className={styles.line81} data-fc="4311:31751" />
              <div className={styles.line75} data-fc="4311:31752" />
              <div className={styles.line72} data-fc="4311:31753" />
              <div className={styles.line69} data-fc="4311:31754" />
              <div className={styles.line66} data-fc="4311:31755" />
              <div className={styles.line63} data-fc="4311:31756" />
              <div className={styles.line61} data-fc="4311:31757" />
              <div className={styles.line60} data-fc="4311:31758" />
              <div className={styles.line79} data-fc="4311:31759" />
              <div className={styles.line76} data-fc="4311:31760" />
              <div className={styles.line57} data-fc="4311:31761" />
              <div className={styles.line71} data-fc="4311:31762" />
              <div className={styles.line68} data-fc="4311:31763" />
              <div className={styles.line65} data-fc="4311:31764" />
              <div className={styles.line56} data-fc="4311:31765" />
              <div className={styles.line54} data-fc="4311:31766" />
              <div className={styles.line52} data-fc="4311:31767" />
              <div className={styles.center} data-fc="4311:31768" />
              <div className={styles.line73} data-fc="4311:31769" />
              <div className={styles.line40} data-fc="4311:31770" />
              <div className={styles.line48} data-fc="4311:31771" />
              <div className={styles.line46} data-fc="4311:31772" />
              <div className={styles.line59} data-fc="4311:31773" />
              <div className={styles.line78} data-fc="4311:31774" />
              <div className={styles.line77} data-fc="4311:31775" />
              <div className={styles.line74} data-fc="4311:31776" />
              <div className={styles.line70} data-fc="4311:31777" />
              <div className={styles.line67} data-fc="4311:31778" />
              <div className={styles.line64} data-fc="4311:31779" />
              <div className={styles.line62} data-fc="4311:31780" />
              <div className={styles.line53} data-fc="4311:31781" />
              <div className={styles.line51} data-fc="4311:31782" />
              <div className={styles.line50} data-fc="4311:31783" />
              <div className={styles.line44} data-fc="4311:31784" />
              <div className={styles.line49} data-fc="4311:31785" />
              <div className={styles.line47} data-fc="4311:31786" />
              <div className={styles.line45} data-fc="4311:31787" />
              <div className={styles.line55} data-fc="4311:31788" />
            </div>
          </div>
        </div>
        <div className={styles.dock} data-fc="4311:31789">
          <div className={styles.tabBar} data-fc="4311:31790">
            <div className={styles.tab} data-fc="4311:31791">
              <svg className={styles.icon12} data-fc="4311:31792" width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_4311_31792" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="-1" y="-1" width="25" height="25">
<path d="M23.5294 -0.941323H-0.941249V23.5293H23.5294V-0.941323Z" fill="white"/>
<foreignObject x="0" y="0" width="0" height="0"><div style={{ backdropFilter: 'blur(1.5px)', clipPath: 'url(#bgblur_0_4311_31792_clip_path)', height: '100%', width: '100%' }}></div></foreignObject><path data-figma-bg-blur-radius="3" d="M15.4741 5.68615C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52122 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735C21.1649 20.5408 20.5408 21.1649 19.7736 21.5559C18.9012 22.0003 17.7582 21.9999 15.4741 21.9999H12.2121C9.92801 21.9999 8.78507 22.0003 7.91264 21.5559C7.14538 21.1649 6.52129 20.5408 6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52122 7.91264 6.13024C8.78507 5.68571 9.92801 5.68615 12.2121 5.68615H15.4741ZM13.8471 9.25479C13.284 9.25479 12.8275 9.71127 12.8275 10.2744V12.8234H10.2745C9.71144 12.8235 9.25486 13.28 9.25486 13.843C9.25486 14.4061 9.71144 14.8625 10.2745 14.8626H12.8275V17.4117C12.8275 17.9748 13.284 18.4313 13.8471 18.4313C14.4102 18.4313 14.8667 17.9748 14.8667 17.4117V14.8626H17.4118C17.9749 14.8626 18.4314 14.4062 18.4314 13.843C18.4314 13.2799 17.9749 12.8234 17.4118 12.8234H14.8667V10.2744C14.8667 9.71127 14.4102 9.25479 13.8471 9.25479Z" fill="black"/>
</mask>
<g mask="url(#mask0_4311_31792)">
<path d="M8.51355 0.747979C10.7194 0.15691 11.8225 -0.139458 12.7802 0.0639226C13.6227 0.242996 14.3875 0.684436 14.9638 1.3245C15.619 2.05214 15.9139 3.15584 16.5051 5.36212L17.3496 8.51355C17.7751 10.102 18.0462 11.1186 18.0894 11.9208C18.8821 12.2003 19.4513 12.9542 19.4515 13.8426C19.4515 14.9688 18.5383 15.8816 17.4123 15.8818H15.8858V17.4112C15.8858 18.5375 14.9728 19.4505 13.8466 19.4505C12.7205 19.4503 11.8074 18.5373 11.8074 17.4112V16.7531L9.58399 17.3496C7.37804 17.9406 6.27494 18.2369 5.31731 18.0336C4.47485 17.8545 3.71002 17.4131 3.13371 16.773C2.47855 16.0454 2.18351 14.9416 1.59234 12.7354L0.747982 9.5839C0.156903 7.37803 -0.139459 6.27494 0.0639247 5.31731C0.242999 4.47485 0.68444 3.71002 1.3245 3.13371C2.05215 2.47857 3.15587 2.18351 5.36212 1.59234L8.51355 0.747979Z" fill="url(#paint0_linear_4311_31792)"/>
</g>
<mask id="mask1_4311_31792" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="5" y="5" width="17" height="17">
<foreignObject x="0" y="0" width="0" height="0"><div style={{ backdropFilter: 'blur(1.5px)', clipPath: 'url(#bgblur_1_4311_31792_clip_path)', height: '100%', width: '100%' }}></div></foreignObject><path data-figma-bg-blur-radius="3" d="M15.4741 5.68615C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52122 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735C21.1649 20.5408 20.5408 21.1649 19.7736 21.5559C18.9012 22.0003 17.7582 21.9999 15.4741 21.9999H12.2121C9.92801 21.9999 8.78507 22.0003 7.91264 21.5559C7.14538 21.1649 6.52129 20.5408 6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52122 7.91264 6.13024C8.78507 5.68571 9.92801 5.68615 12.2121 5.68615H15.4741ZM13.8471 9.25479C13.284 9.25479 12.8275 9.71127 12.8275 10.2744V12.8234H10.2745C9.71144 12.8235 9.25486 13.28 9.25486 13.843C9.25486 14.4061 9.71144 14.8625 10.2745 14.8626H12.8275V17.4117C12.8275 17.9748 13.284 18.4313 13.8471 18.4313C14.4102 18.4313 14.8667 17.9748 14.8667 17.4117V14.8626H17.4118C17.9749 14.8626 18.4314 14.4062 18.4314 13.843C18.4314 13.2799 17.9749 12.8234 17.4118 12.8234H14.8667V10.2744C14.8667 9.71127 14.4102 9.25479 13.8471 9.25479Z" fill="white"/>
</mask>
<g mask="url(#mask1_4311_31792)">
<g filter="url(#filter0_f_4311_31792)">
<path d="M8.51355 0.747979C10.7194 0.15691 11.8225 -0.139458 12.7802 0.0639226C13.6227 0.242996 14.3875 0.684436 14.9638 1.3245C15.619 2.05214 15.9139 3.15584 16.5051 5.36212L17.3496 8.51355C17.7751 10.102 18.0462 11.1186 18.0894 11.9208C18.8821 12.2003 19.4513 12.9542 19.4515 13.8426C19.4515 14.9688 18.5383 15.8816 17.4123 15.8818H15.8858V17.4112C15.8858 18.5375 14.9728 19.4505 13.8466 19.4505C12.7205 19.4503 11.8074 18.5373 11.8074 17.4112V16.7531L9.58399 17.3496C7.37804 17.9406 6.27494 18.2369 5.31731 18.0336C4.47485 17.8545 3.71002 17.4131 3.13371 16.773C2.47855 16.0454 2.18351 14.9416 1.59234 12.7354L0.747982 9.5839C0.156903 7.37803 -0.139459 6.27494 0.0639247 5.31731C0.242999 4.47485 0.68444 3.71002 1.3245 3.13371C2.05215 2.47857 3.15587 2.18351 5.36212 1.59234L8.51355 0.747979Z" fill="url(#paint1_linear_4311_31792)"/>
</g>
</g>
<foreignObject x="2.62739" y="2.62732" width="22.4314" height="22.4314"><div style={{ backdropFilter: 'blur(1.5px)', clipPath: 'url(#bgblur_2_4311_31792_clip_path)', height: '100%', width: '100%' }}></div></foreignObject><path data-figma-bg-blur-radius="3" d="M15.4741 5.68615C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52122 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735C21.1649 20.5408 20.5408 21.1649 19.7736 21.5559C18.9012 22.0003 17.7582 21.9999 15.4741 21.9999H12.2121C9.92801 21.9999 8.78507 22.0003 7.91264 21.5559C7.14538 21.1649 6.52129 20.5408 6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52122 7.91264 6.13024C8.78507 5.68571 9.92801 5.68615 12.2121 5.68615H15.4741ZM13.8471 9.25479C13.284 9.25479 12.8275 9.71127 12.8275 10.2744V12.8234H10.2745C9.71144 12.8235 9.25486 13.28 9.25486 13.843C9.25486 14.4061 9.71144 14.8625 10.2745 14.8626H12.8275V17.4117C12.8275 17.9748 13.284 18.4313 13.8471 18.4313C14.4102 18.4313 14.8667 17.9748 14.8667 17.4117V14.8626H17.4118C17.9749 14.8626 18.4314 14.4062 18.4314 13.843C18.4314 13.2799 17.9749 12.8234 17.4118 12.8234H14.8667V10.2744C14.8667 9.71127 14.4102 9.25479 13.8471 9.25479Z" fill="url(#paint2_linear_4311_31792)"/>
<path d="M15.4741 21.2352V21.9999H12.2121V21.2352H15.4741ZM21.2353 15.474V12.2121C21.2353 11.0575 21.235 10.237 21.1825 9.59534C21.1308 8.96253 21.032 8.57052 20.8738 8.26007C20.5561 7.63671 20.0495 7.12997 19.4261 6.8123C19.1156 6.65413 18.7236 6.55534 18.0908 6.50363C17.4492 6.45121 16.6287 6.45086 15.4741 6.45086H12.2121C11.0575 6.45086 10.2371 6.45121 9.59541 6.50363C8.9626 6.55534 8.57059 6.65413 8.26014 6.8123C7.63678 7.12997 7.13004 7.63671 6.81237 8.26007C6.6542 8.57052 6.55541 8.96253 6.50371 9.59534C6.45129 10.237 6.45093 11.0575 6.45093 12.2121V15.474C6.45093 16.6286 6.45129 17.4491 6.50371 18.0907C6.55541 18.7235 6.6542 19.1155 6.81237 19.426C7.13004 20.0494 7.63678 20.5561 8.26014 20.8738C8.57059 21.0319 8.9626 21.1307 9.59541 21.1824C10.2371 21.2349 11.0575 21.2352 12.2121 21.2352V21.9999L10.6986 21.993C9.48356 21.9738 8.70517 21.9021 8.07992 21.6335L7.91264 21.5559C7.24125 21.2137 6.67946 20.6931 6.28763 20.0543L6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52123 7.91264 6.13024C8.56688 5.79689 9.37324 5.71396 10.6986 5.69312L12.2121 5.68615H15.4741C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52123 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735L21.3986 20.0543C21.0068 20.6931 20.445 21.2137 19.7736 21.5559L19.6063 21.6335C18.7536 21.9998 17.6156 21.9999 15.4741 21.9999V21.2352C16.6287 21.2352 17.4492 21.2349 18.0908 21.1824C18.7236 21.1307 19.1156 21.0319 19.4261 20.8738C20.0495 20.5561 20.5561 20.0494 20.8738 19.426C21.032 19.1155 21.1308 18.7235 21.1825 18.0907C21.235 17.4491 21.2353 16.6286 21.2353 15.474Z" fill="url(#paint3_linear_4311_31792)"/>
<defs>
<clipPath id="bgblur_0_4311_31792_clip_path" transform="translate(0 0)"><path d="M15.4741 5.68615C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52122 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735C21.1649 20.5408 20.5408 21.1649 19.7736 21.5559C18.9012 22.0003 17.7582 21.9999 15.4741 21.9999H12.2121C9.92801 21.9999 8.78507 22.0003 7.91264 21.5559C7.14538 21.1649 6.52129 20.5408 6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52122 7.91264 6.13024C8.78507 5.68571 9.92801 5.68615 12.2121 5.68615H15.4741ZM13.8471 9.25479C13.284 9.25479 12.8275 9.71127 12.8275 10.2744V12.8234H10.2745C9.71144 12.8235 9.25486 13.28 9.25486 13.843C9.25486 14.4061 9.71144 14.8625 10.2745 14.8626H12.8275V17.4117C12.8275 17.9748 13.284 18.4313 13.8471 18.4313C14.4102 18.4313 14.8667 17.9748 14.8667 17.4117V14.8626H17.4118C17.9749 14.8626 18.4314 14.4062 18.4314 13.843C18.4314 13.2799 17.9749 12.8234 17.4118 12.8234H14.8667V10.2744C14.8667 9.71127 14.4102 9.25479 13.8471 9.25479Z"/>
</clipPath><clipPath id="bgblur_1_4311_31792_clip_path" transform="translate(0 0)"><path d="M15.4741 5.68615C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52122 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735C21.1649 20.5408 20.5408 21.1649 19.7736 21.5559C18.9012 22.0003 17.7582 21.9999 15.4741 21.9999H12.2121C9.92801 21.9999 8.78507 22.0003 7.91264 21.5559C7.14538 21.1649 6.52129 20.5408 6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52122 7.91264 6.13024C8.78507 5.68571 9.92801 5.68615 12.2121 5.68615H15.4741ZM13.8471 9.25479C13.284 9.25479 12.8275 9.71127 12.8275 10.2744V12.8234H10.2745C9.71144 12.8235 9.25486 13.28 9.25486 13.843C9.25486 14.4061 9.71144 14.8625 10.2745 14.8626H12.8275V17.4117C12.8275 17.9748 13.284 18.4313 13.8471 18.4313C14.4102 18.4313 14.8667 17.9748 14.8667 17.4117V14.8626H17.4118C17.9749 14.8626 18.4314 14.4062 18.4314 13.843C18.4314 13.2799 17.9749 12.8234 17.4118 12.8234H14.8667V10.2744C14.8667 9.71127 14.4102 9.25479 13.8471 9.25479Z"/>
</clipPath><filter id="filter0_f_4311_31792" x="-4.07844" y="-4.07844" width="27.6084" height="27.6074" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
<feFlood floodOpacity="0" result="BackgroundImageFix"/>
<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
<feGaussianBlur stdDeviation="2" result="effect1_foregroundBlur_4311_31792"/>
</filter>
<clipPath id="bgblur_2_4311_31792_clip_path" transform="translate(-2.62739 -2.62732)"><path d="M15.4741 5.68615C17.7582 5.68615 18.9012 5.68571 19.7736 6.13024C20.5408 6.52122 21.1649 7.1453 21.556 7.91256C22.0004 8.78499 22 9.92794 22 12.2121V15.474C22 17.7581 22.0004 18.9011 21.556 19.7735C21.1649 20.5408 20.5408 21.1649 19.7736 21.5559C18.9012 22.0003 17.7582 21.9999 15.4741 21.9999H12.2121C9.92801 21.9999 8.78507 22.0003 7.91264 21.5559C7.14538 21.1649 6.52129 20.5408 6.13031 19.7735C5.68578 18.9011 5.68622 17.7581 5.68622 15.474V12.2121C5.68622 9.92794 5.68578 8.78499 6.13031 7.91256C6.5213 7.1453 7.14538 6.52122 7.91264 6.13024C8.78507 5.68571 9.92801 5.68615 12.2121 5.68615H15.4741ZM13.8471 9.25479C13.284 9.25479 12.8275 9.71127 12.8275 10.2744V12.8234H10.2745C9.71144 12.8235 9.25486 13.28 9.25486 13.843C9.25486 14.4061 9.71144 14.8625 10.2745 14.8626H12.8275V17.4117C12.8275 17.9748 13.284 18.4313 13.8471 18.4313C14.4102 18.4313 14.8667 17.9748 14.8667 17.4117V14.8626H17.4118C17.9749 14.8626 18.4314 14.4062 18.4314 13.843C18.4314 13.2799 17.9749 12.8234 17.4118 12.8234H14.8667V10.2744C14.8667 9.71127 14.4102 9.25479 13.8471 9.25479Z"/>
</clipPath><linearGradient id="paint0_linear_4311_31792" x1="9.47102" y1="-0.000242583" x2="9.47102" y2="18.9411" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint1_linear_4311_31792" x1="9.47102" y1="-0.000242583" x2="9.47102" y2="18.9411" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint2_linear_4311_31792" x1="13.8431" y1="5.68615" x2="13.8431" y2="21.9999" gradientUnits="userSpaceOnUse">
<stop stopColor="#E3E3E5" stopOpacity="0.6"/>
<stop offset="1" stopColor="#BBBBC0" stopOpacity="0.6"/>
</linearGradient>
<linearGradient id="paint3_linear_4311_31792" x1="13.8431" y1="5.68615" x2="13.8431" y2="15.8823" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
</defs>
</svg>

              <span className={styles.label} data-fc="4311:31804">Add</span>
            </div>
            <div className={styles.tab2} data-fc="4311:31805">
              <svg className={styles.icon13} data-fc="4311:31806" width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_4311_31806" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="-1" y="-2" width="24" height="24">
<path d="M23 -2H-1V22H23V-2Z" fill="white"/>
<path d="M0 9.5C0 5.91015 2.91015 3 6.5 3C10.0898 3 13 5.91015 13 9.5C13 13.0899 10.0898 16 6.5 16C2.91015 16 0 13.0899 0 9.5Z" fill="black"/>
</mask>
<g mask="url(#mask0_4311_31806)">
<path d="M16.2 0C17.8802 0 18.7202 1.19209e-07 19.362 0.32698C19.9265 0.6146 20.3854 1.07354 20.673 1.63803C21 2.27976 21 3.11984 21 4.8V7.2C21 8.8802 21 9.7202 20.673 10.362C20.3854 10.9265 19.9265 11.3854 19.362 11.673C18.7202 12 17.8802 12 16.2 12H13.8C12.1198 12 11.2798 12 10.638 11.673C10.0735 11.3854 9.6146 10.9265 9.327 10.362C9 9.7202 9 8.8802 9 7.2V4.8C9 3.11984 9 2.27976 9.327 1.63803C9.6146 1.07354 10.0735 0.6146 10.638 0.32698C11.2798 1.19209e-07 12.1198 0 13.8 0H16.2Z" fill="url(#paint0_linear_4311_31806)"/>
</g>
<mask id="mask1_4311_31806" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="0" y="3" width="13" height="13">
<path d="M0 9.5C0 5.91015 2.91015 3 6.5 3C10.0898 3 13 5.91015 13 9.5C13 13.0899 10.0898 16 6.5 16C2.91015 16 0 13.0899 0 9.5Z" fill="white"/>
</mask>
<g mask="url(#mask1_4311_31806)">
<g filter="url(#filter0_f_4311_31806)">
<path d="M16.2 0C17.8802 0 18.7202 1.19209e-07 19.362 0.32698C19.9265 0.6146 20.3854 1.07354 20.673 1.63803C21 2.27976 21 3.11984 21 4.8V7.2C21 8.8802 21 9.7202 20.673 10.362C20.3854 10.9265 19.9265 11.3854 19.362 11.673C18.7202 12 17.8802 12 16.2 12H13.8C12.1198 12 11.2798 12 10.638 11.673C10.0735 11.3854 9.6146 10.9265 9.327 10.362C9 9.7202 9 8.8802 9 7.2V4.8C9 3.11984 9 2.27976 9.327 1.63803C9.6146 1.07354 10.0735 0.6146 10.638 0.32698C11.2798 1.19209e-07 12.1198 0 13.8 0H16.2Z" fill="url(#paint1_linear_4311_31806)"/>
</g>
</g>
<path d="M0 9.5C0 5.91015 2.91015 3 6.5 3C10.0898 3 13 5.91015 13 9.5C13 13.0899 10.0898 16 6.5 16C2.91015 16 0 13.0899 0 9.5Z" fill="url(#paint2_linear_4311_31806)"/>
<path d="M12.25 9.5C12.25 6.32436 9.6756 3.75 6.5 3.75C3.32436 3.75 0.75 6.32436 0.75 9.5C0.75 12.6756 3.32436 15.25 6.5 15.25V16C2.91015 16 0 13.0899 0 9.5C0 5.91015 2.91015 3 6.5 3C10.0898 3 13 5.91015 13 9.5C13 13.0899 10.0898 16 6.5 16V15.25C9.6756 15.25 12.25 12.6756 12.25 9.5Z" fill="url(#paint3_linear_4311_31806)"/>
<path d="M15.2096 8.81582C14.4308 7.53307 12.5692 7.53307 11.7904 8.81582L6.84447 16.962C6.03524 18.2949 6.99477 20 8.55404 20H13.5H18.4459C20.0052 20 20.9647 18.2949 20.1555 16.962L15.2096 8.81582Z" fill="url(#paint4_linear_4311_31806)"/>
<defs>
<filter id="filter0_f_4311_31806" x="5" y="-4" width="20" height="20" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
<feFlood floodOpacity="0" result="BackgroundImageFix"/>
<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
<feGaussianBlur stdDeviation="2" result="effect1_foregroundBlur_4311_31806"/>
</filter>
<linearGradient id="paint0_linear_4311_31806" x1="15" y1="-2.048" x2="15" y2="7.8" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint1_linear_4311_31806" x1="15" y1="-2.048" x2="15" y2="7.8" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint2_linear_4311_31806" x1="6.5" y1="3" x2="6.5" y2="16" gradientUnits="userSpaceOnUse">
<stop stopColor="#E3E3E5" stopOpacity="0.6"/>
<stop offset="1" stopColor="#BBBBC0" stopOpacity="0.6"/>
</linearGradient>
<linearGradient id="paint3_linear_4311_31806" x1="6.5" y1="3" x2="6.5" y2="10.528" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
<linearGradient id="paint4_linear_4311_31806" x1="13.5" y1="6.00002" x2="13.5" y2="20" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
</defs>
</svg>

              <span className={styles.label2} data-fc="4311:31819">Shape</span>
            </div>
            <div className={styles.tab3} data-fc="4311:31820">
              <svg className={styles.icon14} data-fc="4311:31821" width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_4311_31821" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="-1" y="-1" width="25" height="25">
<path d="M23.5716 -0.718788H-0.718448V23.5713H23.5716V-0.718788Z" fill="white"/>
<path d="M16.1391 8.60481L13.8494 2.83562C13.3425 1.55828 11.5346 1.55812 11.0274 2.83538L8.7364 8.60481C8.71251 8.6648 8.66514 8.71217 8.60515 8.73606L2.83484 11.0274C1.5577 11.5345 1.5577 13.3421 2.83484 13.8493L8.60515 16.1406C8.66514 16.1645 8.71251 16.2119 8.7364 16.2718L11.0273 22.0413C11.5346 23.3185 13.3424 23.3183 13.8494 22.041L16.1391 16.2718C16.163 16.2117 16.211 16.1644 16.2712 16.1406L22.0421 13.8493C23.3193 13.3422 23.3193 11.5344 22.0421 11.0274L16.2712 8.73606C16.211 8.71223 16.163 8.665 16.1391 8.60481Z" fill="black"/>
</mask>
<g mask="url(#mask0_4311_31821)">
<path d="M12.4387 8.39533C12.9975 8.39533 13.4506 8.84852 13.4507 9.40741V11.4316H15.4749C16.0338 11.4316 16.4869 11.8848 16.487 12.4437C16.4868 13.0024 16.0337 13.4558 15.4749 13.4558H13.4507V15.4799C13.4505 16.0387 12.9974 16.492 12.4387 16.492C11.8799 16.492 11.4268 16.0387 11.4266 15.4799V13.4558H9.4024C8.84364 13.4558 8.39057 13.0024 8.39031 12.4437C8.39038 11.8848 8.84353 11.4317 9.4024 11.4316H11.4266V9.40741C11.4267 8.84855 11.8798 8.39538 12.4387 8.39533ZM5.42522 0.638652C5.76334 -0.212854 6.96909 -0.212914 7.30707 0.638652L8.64333 4.00699C8.65804 4.04377 8.68759 4.07236 8.72438 4.08705L12.0937 5.4253C12.9452 5.76337 12.9452 6.96807 12.0937 7.30616L8.72438 8.6444C8.6876 8.65907 8.65805 8.68771 8.64333 8.72446L7.30707 12.0928C6.96909 12.9443 5.76334 12.9443 5.42522 12.0928L4.08796 8.72446C4.07322 8.6877 4.04372 8.65905 4.00692 8.6444L0.63857 7.30616C-0.212857 6.96807 -0.212857 5.76339 0.63857 5.4253L4.00692 4.08705C4.04374 4.07239 4.07323 4.04378 4.08796 4.00699L5.42522 0.638652Z" fill="url(#paint0_linear_4311_31821)"/>
</g>
<mask id="mask1_4311_31821" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="1" y="1" width="22" height="22">
<path d="M16.1391 8.60481L13.8494 2.83562C13.3425 1.55828 11.5346 1.55812 11.0274 2.83538L8.7364 8.60481C8.71251 8.6648 8.66514 8.71217 8.60515 8.73606L2.83484 11.0274C1.5577 11.5345 1.5577 13.3421 2.83484 13.8493L8.60515 16.1406C8.66514 16.1645 8.71251 16.2119 8.7364 16.2718L11.0273 22.0413C11.5346 23.3185 13.3424 23.3183 13.8494 22.041L16.1391 16.2718C16.163 16.2117 16.211 16.1644 16.2712 16.1406L22.0421 13.8493C23.3193 13.3422 23.3193 11.5344 22.0421 11.0274L16.2712 8.73606C16.211 8.71223 16.163 8.665 16.1391 8.60481Z" fill="white"/>
</mask>
<g mask="url(#mask1_4311_31821)">
<g filter="url(#filter0_f_4311_31821)">
<path d="M12.4387 8.39533C12.9975 8.39533 13.4507 8.84852 13.4508 9.40741V11.4316H15.4749C16.0338 11.4316 16.4869 11.8848 16.487 12.4437C16.4868 13.0024 16.0337 13.4558 15.4749 13.4558H13.4508V15.4799C13.4506 16.0387 12.9974 16.492 12.4387 16.492C11.8799 16.492 11.4268 16.0387 11.4266 15.4799V13.4558H9.40241C8.84365 13.4558 8.39058 13.0024 8.39033 12.4437C8.3904 11.8848 8.84354 11.4317 9.40241 11.4316H11.4266V9.40741C11.4267 8.84855 11.8798 8.39538 12.4387 8.39533ZM5.42523 0.638652C5.76336 -0.212854 6.96911 -0.212914 7.30708 0.638652L8.64335 4.00699C8.65806 4.04377 8.68761 4.07236 8.7244 4.08705L12.0938 5.4253C12.9452 5.76337 12.9452 6.96807 12.0938 7.30616L8.7244 8.6444C8.68762 8.65907 8.65807 8.68771 8.64335 8.72446L7.30708 12.0928C6.96911 12.9443 5.76336 12.9443 5.42523 12.0928L4.08797 8.72446C4.07324 8.6877 4.04374 8.65905 4.00694 8.6444L0.638586 7.30616C-0.212841 6.96807 -0.212841 5.76339 0.638586 5.4253L4.00694 4.08705C4.04376 4.07239 4.07325 4.04378 4.08797 4.00699L5.42523 0.638652Z" fill="url(#paint1_linear_4311_31821)"/>
</g>
</g>
<path d="M16.1391 8.60481L13.8494 2.83562C13.3425 1.55828 11.5346 1.55812 11.0274 2.83538L8.7364 8.60481C8.71251 8.6648 8.66514 8.71217 8.60515 8.73606L2.83484 11.0274C1.5577 11.5345 1.5577 13.3421 2.83484 13.8493L8.60515 16.1406C8.66514 16.1645 8.71251 16.2119 8.7364 16.2718L11.0273 22.0413C11.5346 23.3185 13.3424 23.3183 13.8494 22.041L16.1391 16.2718C16.163 16.2117 16.211 16.1644 16.2712 16.1406L22.0421 13.8493C23.3193 13.3422 23.3193 11.5344 22.0421 11.0274L16.2712 8.73606C16.211 8.71223 16.163 8.665 16.1391 8.60481Z" fill="url(#paint2_linear_4311_31821)"/>
<path d="M11.0272 2.83539C11.5343 1.55825 13.3418 1.55837 13.8489 2.83539L16.1389 8.60448C16.1629 8.66467 16.2112 8.71211 16.2714 8.73593L22.0415 11.027C23.3187 11.534 23.3187 13.3426 22.0415 13.8498L16.2714 16.1407L16.2289 16.1625C16.1886 16.1887 16.157 16.2269 16.1389 16.2722L13.8489 22.0413L13.7976 22.157C13.2483 23.2796 11.6277 23.2798 11.0785 22.157L11.0272 22.0413L8.73612 16.2722C8.71225 16.2122 8.66465 16.1646 8.60468 16.1407L2.83461 13.8498C1.55746 13.3426 1.55746 11.5341 2.83461 11.027L8.60468 8.73593C8.66465 8.71205 8.71225 8.66446 8.73612 8.60448L11.0272 2.83539ZM13.1443 3.1161C12.8909 2.47755 11.9867 2.47688 11.7328 3.1151L9.44177 8.88517C9.35338 9.1073 9.18821 9.28953 8.97828 9.39912L8.88537 9.44164L3.1153 11.7327C2.47672 11.9862 2.47673 12.8904 3.1153 13.144L8.88537 15.4351C9.10749 15.5235 9.28973 15.6886 9.39931 15.8986L9.44177 15.9916L11.7328 21.7616C11.9867 22.3998 12.8898 22.3992 13.1433 21.7606L15.4333 15.9916L15.4767 15.8976C15.588 15.6854 15.7715 15.5221 15.9908 15.4351L21.7618 13.144C22.4004 12.8905 22.4004 11.9862 21.7618 11.7327L15.9908 9.44164C15.7716 9.35456 15.5879 9.19122 15.4767 8.97907L15.4333 8.88517L13.1443 3.1161Z" fill="url(#paint3_linear_4311_31821)"/>
<defs>
<filter id="filter0_f_4311_31821" x="-4.04833" y="-4.04834" width="24.5837" height="24.5887" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
<feFlood floodOpacity="0" result="BackgroundImageFix"/>
<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
<feGaussianBlur stdDeviation="2" result="effect1_foregroundBlur_4311_31821"/>
</filter>
<linearGradient id="paint0_linear_4311_31821" x1="8.24356" y1="-0.000227086" x2="8.24356" y2="12.9443" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint1_linear_4311_31821" x1="8.24358" y1="-0.000227086" x2="8.24358" y2="12.9443" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint2_linear_4311_31821" x1="12.4387" y1="-0.718783" x2="12.4387" y2="25.5954" gradientUnits="userSpaceOnUse">
<stop stopColor="#E3E3E5" stopOpacity="0.6"/>
<stop offset="1" stopColor="#BBBBC0" stopOpacity="0.6"/>
</linearGradient>
<linearGradient id="paint3_linear_4311_31821" x1="12.4376" y1="1.87721" x2="12.4376" y2="12.9444" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
</defs>
</svg>

              <span className={styles.label3} data-fc="4311:31833">Effect</span>
            </div>
            <div className={styles.tab4} data-fc="4311:31834">
              <svg className={styles.icon15} data-fc="4311:31835" width="21" height="18" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_4311_31835" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="-2" y="-3" width="24" height="24">
<path d="M22 -3H-2V21H22V-3Z" fill="white"/>
<path d="M12.2168 4.89746C12.7172 4.68454 13.2828 4.68453 13.7832 4.89746C14.3562 5.1414 14.8052 5.85075 15.7031 7.2686L19.3887 13.0879C20.4031 14.6896 20.9108 15.4908 20.8604 16.1523C20.8163 16.7287 20.525 17.258 20.0615 17.6035C19.5296 18.0001 18.5815 18 16.6855 18H9.3145C7.41854 18 6.47039 18.0001 5.93848 17.6035C5.47504 17.258 5.18368 16.7287 5.13965 16.1523C5.08925 15.4908 5.59692 14.6896 6.61133 13.0879L10.2969 7.2686C11.1948 5.85076 11.6438 5.1414 12.2168 4.89746ZM5 2.5C6.38071 2.5 7.5 3.61929 7.5 5C7.5 6.38071 6.38071 7.5 5 7.5C3.61929 7.5 2.5 6.38071 2.5 5C2.5 3.61929 3.61929 2.5 5 2.5Z" fill="black"/>
</mask>
<g mask="url(#mask0_4311_31835)">
<path d="M16 0C18.2091 0 20 1.79086 20 4V12C20 14.2091 18.2091 16 16 16H4C1.79086 16 0 14.2091 0 12V4C0 1.79086 1.79086 0 4 0H16Z" fill="url(#paint0_linear_4311_31835)"/>
</g>
<mask id="mask1_4311_31835" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="2" y="2" width="19" height="16">
<path d="M12.2168 4.89746C12.7172 4.68454 13.2828 4.68453 13.7832 4.89746C14.3562 5.1414 14.8052 5.85075 15.7031 7.2686L19.3887 13.0879C20.4031 14.6896 20.9108 15.4908 20.8604 16.1523C20.8163 16.7287 20.525 17.258 20.0615 17.6035C19.5296 18.0001 18.5815 18 16.6855 18H9.3145C7.41854 18 6.47039 18.0001 5.93848 17.6035C5.47504 17.258 5.18368 16.7287 5.13965 16.1523C5.08925 15.4908 5.59692 14.6896 6.61133 13.0879L10.2969 7.2686C11.1948 5.85076 11.6438 5.1414 12.2168 4.89746ZM5 2.5C6.38071 2.5 7.5 3.61929 7.5 5C7.5 6.38071 6.38071 7.5 5 7.5C3.61929 7.5 2.5 6.38071 2.5 5C2.5 3.61929 3.61929 2.5 5 2.5Z" fill="white"/>
</mask>
<g mask="url(#mask1_4311_31835)">
<g filter="url(#filter0_f_4311_31835)">
<path d="M16 0C18.2091 0 20 1.79086 20 4V12C20 14.2091 18.2091 16 16 16H4C1.79086 16 0 14.2091 0 12V4C0 1.79086 1.79086 0 4 0H16Z" fill="url(#paint1_linear_4311_31835)"/>
</g>
</g>
<path d="M12.2168 4.89746C12.7172 4.68454 13.2828 4.68453 13.7832 4.89746C14.3562 5.1414 14.8052 5.85075 15.7031 7.2686L19.3887 13.0879C20.4031 14.6896 20.9108 15.4908 20.8604 16.1523C20.8163 16.7287 20.525 17.258 20.0615 17.6035C19.5296 18.0001 18.5815 18 16.6855 18H9.3145C7.41854 18 6.47039 18.0001 5.93848 17.6035C5.47504 17.258 5.18368 16.7287 5.13965 16.1523C5.08925 15.4908 5.59692 14.6896 6.61133 13.0879L10.2969 7.2686C11.1948 5.85076 11.6438 5.1414 12.2168 4.89746ZM5 2.5C6.38071 2.5 7.5 3.61929 7.5 5C7.5 6.38071 6.38071 7.5 5 7.5C3.61929 7.5 2.5 6.38071 2.5 5C2.5 3.61929 3.61929 2.5 5 2.5Z" fill="url(#paint2_linear_4311_31835)"/>
<path d="M16.6853 17.2497V17.9997H9.3142V17.2497H16.6853ZM12.2166 4.8981C12.7171 4.68501 13.2834 4.68501 13.7839 4.8981C14.3567 5.14225 14.8062 5.85079 15.7039 7.2682L19.3894 13.0876C20.4038 14.6893 20.9105 15.4905 20.8601 16.152L20.8328 16.3659C20.7412 16.8581 20.4669 17.3008 20.0613 17.6032C19.5294 17.9997 18.5812 17.9997 16.6853 17.9997V17.2497C17.6479 17.2497 18.3181 17.2494 18.8162 17.2038C19.3199 17.1576 19.5179 17.0734 19.613 17.0026C19.9027 16.7867 20.0845 16.4556 20.1121 16.0954C20.1211 15.9772 20.0869 15.7648 19.8562 15.3141C19.6283 14.8689 19.2707 14.3023 18.7556 13.4889L15.0701 7.6696C14.6133 6.94839 14.2974 6.45162 14.0271 6.10025C13.7568 5.74889 13.5978 5.63351 13.49 5.58756C13.1772 5.4544 12.8233 5.45444 12.5105 5.58756C12.4027 5.63346 12.2437 5.74887 11.9734 6.10025C11.7031 6.45159 11.3871 6.94848 10.9304 7.6696L7.24488 13.4889C6.72982 14.3022 6.3722 14.8689 6.14429 15.3141C5.91358 15.7648 5.87845 15.9772 5.88746 16.0954C5.91502 16.4556 6.09781 16.7867 6.38746 17.0026C6.48268 17.0734 6.68021 17.1576 7.18336 17.2038C7.68136 17.2494 8.3516 17.2497 9.3142 17.2497V17.9997C7.53729 17.9997 6.59308 18.0001 6.04371 17.6735L5.93922 17.6032C5.53362 17.3008 5.25929 16.8581 5.16773 16.3659L5.14039 16.152C5.08999 15.4905 5.59668 14.6893 6.61109 13.0876L10.2966 7.2682C11.1383 5.93932 11.5855 5.23305 12.1101 4.94889L12.2166 4.8981Z" fill="url(#paint3_linear_4311_31835)"/>
<path d="M6.75 5C6.75 4.0335 5.9665 3.25 5 3.25C4.0335 3.25 3.25 4.0335 3.25 5C3.25 5.9665 4.0335 6.75 5 6.75V7.5C3.61929 7.5 2.5 6.38071 2.5 5C2.5 3.61929 3.61929 2.5 5 2.5C6.38071 2.5 7.5 3.61929 7.5 5C7.5 6.38071 6.38071 7.5 5 7.5V6.75C5.9665 6.75 6.75 5.9665 6.75 5Z" fill="url(#paint4_linear_4311_31835)"/>
<defs>
<filter id="filter0_f_4311_31835" x="-4" y="-4" width="28" height="24" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
<feFlood floodOpacity="0" result="BackgroundImageFix"/>
<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
<feGaussianBlur stdDeviation="2" result="effect1_foregroundBlur_4311_31835"/>
</filter>
<linearGradient id="paint0_linear_4311_31835" x1="10" y1="0" x2="10" y2="16" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint1_linear_4311_31835" x1="10" y1="0" x2="10" y2="16" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint2_linear_4311_31835" x1="11.682" y1="2.5" x2="11.682" y2="18" gradientUnits="userSpaceOnUse">
<stop stopColor="#E3E3E5" stopOpacity="0.6"/>
<stop offset="1" stopColor="#BBBBC0" stopOpacity="0.6"/>
</linearGradient>
<linearGradient id="paint3_linear_4311_31835" x1="13" y1="4.738" x2="13" y2="12.418" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
<linearGradient id="paint4_linear_4311_31835" x1="5" y1="2.5" x2="5" y2="6" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
</defs>
</svg>

              <span className={styles.label4} data-fc="4311:31848">Tune</span>
            </div>
            <div className={styles.tab5} data-fc="4311:31849">
              <svg className={styles.icon16} data-fc="4311:31850" width="24" height="21" viewBox="0 0 24 21" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_4311_31850" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24">
<path d="M24 0H0V24H24V0Z" fill="white"/>
<path fillRule="evenodd" clipRule="evenodd" d="M12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3ZM12.7954 11.2046C12.3561 10.7653 11.6439 10.7653 11.2046 11.2046C10.7653 11.6439 10.7653 12.3561 11.2046 12.7954L15.1421 16.7329L15.2278 16.8098C15.6697 17.1702 16.321 17.1448 16.7329 16.7329C17.1448 16.321 17.1702 15.6697 16.8098 15.2278L16.7329 15.1421L12.7954 11.2046Z" fill="black"/>
</mask>
<g mask="url(#mask0_4311_31850)">
<path d="M3.51953 19.0693C3.91006 18.6788 4.54308 18.6788 4.93359 19.0693C5.3241 19.4599 5.32413 20.0929 4.93359 20.4834L4.92676 20.4902C4.53623 20.8807 3.90321 20.8807 3.5127 20.4902C3.1222 20.0997 3.12221 19.4667 3.5127 19.0762L3.51953 19.0693ZM19.0762 19.0693C19.4422 18.7033 20.0213 18.6799 20.4141 19L20.4902 19.0693L20.4971 19.0762L20.5664 19.1523C20.8864 19.5451 20.8631 20.1242 20.4971 20.4902C20.1065 20.8806 19.4735 20.8807 19.083 20.4902L19.0762 20.4834L19.0078 20.4072C18.6873 20.0145 18.7101 19.4355 19.0762 19.0693ZM10.5859 10.5859C11.367 9.80489 12.633 9.80489 13.4141 10.5859L17.4141 14.5859L17.5518 14.7373C18.1926 15.5229 18.1463 16.6818 17.4141 17.4141C16.6818 18.1463 15.5229 18.1926 14.7373 17.5518L14.5859 17.4141L10.5859 13.4141C9.80489 12.633 9.80489 11.367 10.5859 10.5859ZM1.00977 11C1.56205 11 2.00977 11.4477 2.00977 12C2.00977 12.5523 1.56205 13 1.00977 13H1C0.447715 13 0 12.5523 0 12C0 11.4477 0.447715 11 1 11H1.00977ZM23.0098 11C23.562 11 24.0098 11.4477 24.0098 12C24.0098 12.5523 23.562 13 23.0098 13H23C22.4477 13 22 12.5523 22 12C22 11.4477 22.4477 11 23 11H23.0098ZM3.51953 3.5127C3.88578 3.14645 4.46562 3.12363 4.8584 3.44434L4.93359 3.5127L4.94141 3.51953L5.00977 3.5957C5.32994 3.98834 5.30714 4.56748 4.94141 4.93359C4.55088 5.32412 3.91689 5.32412 3.52637 4.93359L3.51953 4.92676C3.12919 4.53626 3.12917 3.90318 3.51953 3.5127ZM19.0762 3.5127C19.4667 3.12221 20.0997 3.1222 20.4902 3.5127C20.8807 3.90321 20.8807 4.53623 20.4902 4.92676L20.4834 4.93359C20.0929 5.32413 19.4599 5.32411 19.0693 4.93359C18.6788 4.54308 18.6788 3.91006 19.0693 3.51953L19.0762 3.5127ZM12 0C12.5523 5.15403e-06 13 0.447718 13 1V1.00977C13 1.56205 12.5523 2.00976 12 2.00977C11.4477 2.00977 11 1.56205 11 1.00977V1C11 0.447715 11.4477 0 12 0Z" fill="url(#paint0_linear_4311_31850)"/>
</g>
<mask id="mask1_4311_31850" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="3" y="3" width="18" height="18">
<path fillRule="evenodd" clipRule="evenodd" d="M12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3ZM12.7954 11.2046C12.3561 10.7653 11.6439 10.7653 11.2046 11.2046C10.7653 11.6439 10.7653 12.3561 11.2046 12.7954L15.1421 16.7329L15.2278 16.8098C15.6697 17.1702 16.321 17.1448 16.7329 16.7329C17.1448 16.321 17.1702 15.6697 16.8098 15.2278L16.7329 15.1421L12.7954 11.2046Z" fill="white"/>
</mask>
<g mask="url(#mask1_4311_31850)">
<g filter="url(#filter0_f_4311_31850)">
<path d="M3.51953 19.0693C3.91006 18.6788 4.54308 18.6788 4.93359 19.0693C5.3241 19.4599 5.32413 20.0929 4.93359 20.4834L4.92676 20.4902C4.53623 20.8807 3.90321 20.8807 3.5127 20.4902C3.1222 20.0997 3.12221 19.4667 3.5127 19.0762L3.51953 19.0693ZM19.0762 19.0693C19.4422 18.7033 20.0213 18.6799 20.4141 19L20.4902 19.0693L20.4971 19.0762L20.5664 19.1523C20.8864 19.5451 20.8631 20.1242 20.4971 20.4902C20.1065 20.8806 19.4735 20.8807 19.083 20.4902L19.0762 20.4834L19.0078 20.4072C18.6873 20.0145 18.7101 19.4355 19.0762 19.0693ZM10.5859 10.5859C11.367 9.80489 12.633 9.80489 13.4141 10.5859L17.4141 14.5859L17.5518 14.7373C18.1926 15.5229 18.1463 16.6818 17.4141 17.4141C16.6818 18.1463 15.5229 18.1926 14.7373 17.5518L14.5859 17.4141L10.5859 13.4141C9.80489 12.633 9.80489 11.367 10.5859 10.5859ZM1.00977 11C1.56205 11 2.00977 11.4477 2.00977 12C2.00977 12.5523 1.56205 13 1.00977 13H1C0.447715 13 0 12.5523 0 12C0 11.4477 0.447715 11 1 11H1.00977ZM23.0098 11C23.562 11 24.0098 11.4477 24.0098 12C24.0098 12.5523 23.562 13 23.0098 13H23C22.4477 13 22 12.5523 22 12C22 11.4477 22.4477 11 23 11H23.0098ZM3.51953 3.5127C3.88578 3.14645 4.46562 3.12363 4.8584 3.44434L4.93359 3.5127L4.94141 3.51953L5.00977 3.5957C5.32994 3.98834 5.30714 4.56748 4.94141 4.93359C4.55088 5.32412 3.91689 5.32412 3.52637 4.93359L3.51953 4.92676C3.12919 4.53626 3.12917 3.90318 3.51953 3.5127ZM19.0762 3.5127C19.4667 3.12221 20.0997 3.1222 20.4902 3.5127C20.8807 3.90321 20.8807 4.53623 20.4902 4.92676L20.4834 4.93359C20.0929 5.32413 19.4599 5.32411 19.0693 4.93359C18.6788 4.54308 18.6788 3.91006 19.0693 3.51953L19.0762 3.5127ZM12 0C12.5523 5.15403e-06 13 0.447718 13 1V1.00977C13 1.56205 12.5523 2.00976 12 2.00977C11.4477 2.00977 11 1.56205 11 1.00977V1C11 0.447715 11.4477 0 12 0Z" fill="url(#paint1_linear_4311_31850)"/>
</g>
</g>
<path fillRule="evenodd" clipRule="evenodd" d="M12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3ZM12.7954 11.2046C12.3561 10.7653 11.6439 10.7653 11.2046 11.2046C10.7653 11.6439 10.7653 12.3561 11.2046 12.7954L15.1421 16.7329L15.2278 16.8098C15.6697 17.1702 16.321 17.1448 16.7329 16.7329C17.1448 16.321 17.1702 15.6697 16.8098 15.2278L16.7329 15.1421L12.7954 11.2046Z" fill="url(#paint2_linear_4311_31850)"/>
<path d="M12 3C16.9706 3 21 7.02944 21 12C21 14.8278 19.695 17.3501 17.6553 19H16.3652C18.6976 17.5424 20.25 14.9531 20.25 12C20.25 7.44365 16.5563 3.75 12 3.75C7.44365 3.75 3.75 7.44365 3.75 12C3.75 14.9531 5.30238 17.5424 7.63477 19H6.34473C4.30501 17.3501 3 14.8278 3 12C3 7.02944 7.02944 3 12 3Z" fill="url(#paint3_linear_4311_31850)"/>
<defs>
<filter id="filter0_f_4311_31850" x="-4" y="-4" width="32.0098" height="28.7831" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
<feFlood floodOpacity="0" result="BackgroundImageFix"/>
<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
<feGaussianBlur stdDeviation="2" result="effect1_foregroundBlur_4311_31850"/>
</filter>
<linearGradient id="paint0_linear_4311_31850" x1="12.005" y1="0" x2="12.005" y2="20.783" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint1_linear_4311_31850" x1="12.005" y1="0" x2="12.005" y2="20.783" gradientUnits="userSpaceOnUse">
<stop stopColor="#575757"/>
<stop offset="1" stopColor="#151515"/>
</linearGradient>
<linearGradient id="paint2_linear_4311_31850" x1="12" y1="3" x2="12" y2="21" gradientUnits="userSpaceOnUse">
<stop stopColor="#E3E3E5" stopOpacity="0.6"/>
<stop offset="1" stopColor="#BBBEC0" stopOpacity="0.6"/>
</linearGradient>
<linearGradient id="paint3_linear_4311_31850" x1="12" y1="3" x2="12" y2="15.5" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
</defs>
</svg>

              <span className={styles.label5} data-fc="4311:31862">Edit</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
