// Auto-generated by build-scan.mjs · ONEMO Design System v2.3.1 · structural token names, values reference CSS vars.
export const tokens = {
  "primCol": {
    "base": {
      "white": "var(--prim-col-base-white)",
      "black": "var(--prim-col-base-black)",
      "white-constant": "var(--prim-col-base-white-constant)",
      "black-constant": "var(--prim-col-base-black-constant)",
      "transparent": "var(--prim-col-base-transparent)",
      "brand-white": "var(--prim-col-base-brand-white)",
      "brand-black": "var(--prim-col-base-brand-black)",
      "brand-white-constant": "var(--prim-col-base-brand-white-constant)",
      "brand-black-constant": "var(--prim-col-base-brand-black-constant)",
      "brand-graphite-constant": "var(--prim-col-base-brand-graphite-constant)",
      "brand-off-white-constant": "var(--prim-col-base-brand-off-white-constant)"
    },
    "grey": {
      "1": "var(--prim-col-grey-1)",
      "2": "var(--prim-col-grey-2)",
      "3": "var(--prim-col-grey-3)",
      "4": "var(--prim-col-grey-4)",
      "5": "var(--prim-col-grey-5)",
      "6": "var(--prim-col-grey-6)",
      "7": "var(--prim-col-grey-7)",
      "8": "var(--prim-col-grey-8)",
      "9": "var(--prim-col-grey-9)",
      "10": "var(--prim-col-grey-10)",
      "11": "var(--prim-col-grey-11)",
      "12": "var(--prim-col-grey-12)"
    },
    "raspberry-plum": {
      "1": "var(--prim-col-raspberry-plum-1)",
      "2": "var(--prim-col-raspberry-plum-2)",
      "3": "var(--prim-col-raspberry-plum-3)",
      "4": "var(--prim-col-raspberry-plum-4)",
      "5": "var(--prim-col-raspberry-plum-5)",
      "6": "var(--prim-col-raspberry-plum-6)",
      "7": "var(--prim-col-raspberry-plum-7)",
      "8": "var(--prim-col-raspberry-plum-8)",
      "9": "var(--prim-col-raspberry-plum-9)",
      "10": "var(--prim-col-raspberry-plum-10)",
      "11": "var(--prim-col-raspberry-plum-11)",
      "12": "var(--prim-col-raspberry-plum-12)"
    },
    "indigo-bloom": {
      "1": "var(--prim-col-indigo-bloom-1)",
      "2": "var(--prim-col-indigo-bloom-2)",
      "3": "var(--prim-col-indigo-bloom-3)",
      "4": "var(--prim-col-indigo-bloom-4)",
      "5": "var(--prim-col-indigo-bloom-5)",
      "6": "var(--prim-col-indigo-bloom-6)",
      "7": "var(--prim-col-indigo-bloom-7)",
      "8": "var(--prim-col-indigo-bloom-8)",
      "9": "var(--prim-col-indigo-bloom-9)",
      "10": "var(--prim-col-indigo-bloom-10)",
      "11": "var(--prim-col-indigo-bloom-11)",
      "12": "var(--prim-col-indigo-bloom-12)"
    },
    "lime-moss": {
      "1": "var(--prim-col-lime-moss-1)",
      "2": "var(--prim-col-lime-moss-2)",
      "3": "var(--prim-col-lime-moss-3)",
      "4": "var(--prim-col-lime-moss-4)",
      "5": "var(--prim-col-lime-moss-5)",
      "6": "var(--prim-col-lime-moss-6)",
      "7": "var(--prim-col-lime-moss-7)",
      "8": "var(--prim-col-lime-moss-8)",
      "9": "var(--prim-col-lime-moss-9)",
      "10": "var(--prim-col-lime-moss-10)",
      "11": "var(--prim-col-lime-moss-11)",
      "12": "var(--prim-col-lime-moss-12)"
    },
    "tomato-jam": {
      "1": "var(--prim-col-tomato-jam-1)",
      "2": "var(--prim-col-tomato-jam-2)",
      "3": "var(--prim-col-tomato-jam-3)",
      "4": "var(--prim-col-tomato-jam-4)",
      "5": "var(--prim-col-tomato-jam-5)",
      "6": "var(--prim-col-tomato-jam-6)",
      "7": "var(--prim-col-tomato-jam-7)",
      "8": "var(--prim-col-tomato-jam-8)",
      "9": "var(--prim-col-tomato-jam-9)",
      "10": "var(--prim-col-tomato-jam-10)",
      "11": "var(--prim-col-tomato-jam-11)",
      "12": "var(--prim-col-tomato-jam-12)"
    },
    "golden-glow": {
      "1": "var(--prim-col-golden-glow-1)",
      "2": "var(--prim-col-golden-glow-2)",
      "3": "var(--prim-col-golden-glow-3)",
      "4": "var(--prim-col-golden-glow-4)",
      "5": "var(--prim-col-golden-glow-5)",
      "6": "var(--prim-col-golden-glow-6)",
      "7": "var(--prim-col-golden-glow-7)",
      "8": "var(--prim-col-golden-glow-8)",
      "9": "var(--prim-col-golden-glow-9)",
      "10": "var(--prim-col-golden-glow-10)",
      "11": "var(--prim-col-golden-glow-11)",
      "12": "var(--prim-col-golden-glow-12)"
    },
    "persian-blue": {
      "1": "var(--prim-col-persian-blue-1)",
      "2": "var(--prim-col-persian-blue-2)",
      "3": "var(--prim-col-persian-blue-3)",
      "4": "var(--prim-col-persian-blue-4)",
      "5": "var(--prim-col-persian-blue-5)",
      "6": "var(--prim-col-persian-blue-6)",
      "7": "var(--prim-col-persian-blue-7)",
      "8": "var(--prim-col-persian-blue-8)",
      "9": "var(--prim-col-persian-blue-9)",
      "10": "var(--prim-col-persian-blue-10)",
      "11": "var(--prim-col-persian-blue-11)",
      "12": "var(--prim-col-persian-blue-12)"
    },
    "jade-green": {
      "1": "var(--prim-col-jade-green-1)",
      "2": "var(--prim-col-jade-green-2)",
      "3": "var(--prim-col-jade-green-3)",
      "4": "var(--prim-col-jade-green-4)",
      "5": "var(--prim-col-jade-green-5)",
      "6": "var(--prim-col-jade-green-6)",
      "7": "var(--prim-col-jade-green-7)",
      "8": "var(--prim-col-jade-green-8)",
      "9": "var(--prim-col-jade-green-9)",
      "10": "var(--prim-col-jade-green-10)",
      "11": "var(--prim-col-jade-green-11)",
      "12": "var(--prim-col-jade-green-12)"
    },
    "blue-green": {
      "1": "var(--prim-col-blue-green-1)",
      "2": "var(--prim-col-blue-green-2)",
      "3": "var(--prim-col-blue-green-3)",
      "4": "var(--prim-col-blue-green-4)",
      "5": "var(--prim-col-blue-green-5)",
      "6": "var(--prim-col-blue-green-6)",
      "7": "var(--prim-col-blue-green-7)",
      "8": "var(--prim-col-blue-green-8)",
      "9": "var(--prim-col-blue-green-9)",
      "10": "var(--prim-col-blue-green-10)",
      "11": "var(--prim-col-blue-green-11)",
      "12": "var(--prim-col-blue-green-12)"
    },
    "grey-neutral": {
      "1": "var(--prim-col-grey-neutral-1)",
      "2": "var(--prim-col-grey-neutral-2)",
      "3": "var(--prim-col-grey-neutral-3)",
      "4": "var(--prim-col-grey-neutral-4)",
      "5": "var(--prim-col-grey-neutral-5)",
      "6": "var(--prim-col-grey-neutral-6)",
      "7": "var(--prim-col-grey-neutral-7)",
      "8": "var(--prim-col-grey-neutral-8)",
      "9": "var(--prim-col-grey-neutral-9)",
      "10": "var(--prim-col-grey-neutral-10)",
      "11": "var(--prim-col-grey-neutral-11)",
      "12": "var(--prim-col-grey-neutral-12)"
    }
  },
  "primDim": {
    "0": "var(--prim-dim-0)",
    "1": "var(--prim-dim-1)",
    "2": "var(--prim-dim-2)",
    "3": "var(--prim-dim-3)",
    "4": "var(--prim-dim-4)",
    "6": "var(--prim-dim-6)",
    "8": "var(--prim-dim-8)",
    "10": "var(--prim-dim-10)",
    "12": "var(--prim-dim-12)",
    "14": "var(--prim-dim-14)",
    "16": "var(--prim-dim-16)",
    "18": "var(--prim-dim-18)",
    "20": "var(--prim-dim-20)",
    "24": "var(--prim-dim-24)",
    "28": "var(--prim-dim-28)",
    "32": "var(--prim-dim-32)",
    "36": "var(--prim-dim-36)",
    "40": "var(--prim-dim-40)",
    "44": "var(--prim-dim-44)",
    "48": "var(--prim-dim-48)",
    "56": "var(--prim-dim-56)",
    "64": "var(--prim-dim-64)",
    "68": "var(--prim-dim-68)",
    "72": "var(--prim-dim-72)",
    "80": "var(--prim-dim-80)",
    "96": "var(--prim-dim-96)",
    "128": "var(--prim-dim-128)",
    "160": "var(--prim-dim-160)",
    "192": "var(--prim-dim-192)",
    "224": "var(--prim-dim-224)",
    "256": "var(--prim-dim-256)",
    "320": "var(--prim-dim-320)",
    "375": "var(--prim-dim-375)",
    "384": "var(--prim-dim-384)",
    "480": "var(--prim-dim-480)",
    "560": "var(--prim-dim-560)",
    "640": "var(--prim-dim-640)",
    "720": "var(--prim-dim-720)",
    "768": "var(--prim-dim-768)",
    "1024": "var(--prim-dim-1024)",
    "1280": "var(--prim-dim-1280)",
    "1440": "var(--prim-dim-1440)",
    "1600": "var(--prim-dim-1600)",
    "1920": "var(--prim-dim-1920)",
    "9999": "var(--prim-dim-9999)"
  },
  "primType": {
    "basic": {
      "satoshi": "var(--prim-type-basic-satoshi)",
      "chillax": "var(--prim-type-basic-chillax)",
      "nippo": "var(--prim-type-basic-nippo)",
      "jetbrains-mono": "var(--prim-type-basic-jetbrains-mono)",
      "oxanium": "var(--prim-type-basic-oxanium)"
    },
    "deco": {
      "chaumont": "var(--prim-type-deco-chaumont)",
      "pelowlawa": "var(--prim-type-deco-pelowlawa)",
      "array": "var(--prim-type-deco-array)",
      "random": "var(--prim-type-deco-random)",
      "pyxis": "var(--prim-type-deco-pyxis)",
      "bt-super": "var(--prim-type-deco-bt-super)",
      "striper": "var(--prim-type-deco-striper)",
      "typefesse": "var(--prim-type-deco-typefesse)",
      "modelo": "var(--prim-type-deco-modelo)",
      "anthony": "var(--prim-type-deco-anthony)",
      "half": "var(--prim-type-deco-half)",
      "kollektiiv": "var(--prim-type-deco-kollektiiv)",
      "plantasia-myrtillo": "var(--prim-type-deco-plantasia-myrtillo)",
      "cr-dible": "var(--prim-type-deco-cr-dible)",
      "tanker": "var(--prim-type-deco-tanker)",
      "boxing": "var(--prim-type-deco-boxing)",
      "fun-ghetto": "var(--prim-type-deco-fun-ghetto)",
      "new-value": "var(--prim-type-deco-new-value)",
      "kobata": "var(--prim-type-deco-kobata)",
      "lobular": "var(--prim-type-deco-lobular)",
      "sniglet": "var(--prim-type-deco-sniglet)",
      "betatrone": "var(--prim-type-deco-betatrone)",
      "electric-blue": "var(--prim-type-deco-electric-blue)"
    }
  },
  "primTrack": {
    "neg-10": "var(--prim-track-neg-10)",
    "neg-8": "var(--prim-track-neg-8)",
    "neg-6": "var(--prim-track-neg-6)",
    "neg-4": "var(--prim-track-neg-4)",
    "neg-3-5": "var(--prim-track-neg-3-5)",
    "neg-3": "var(--prim-track-neg-3)",
    "neg-2-5": "var(--prim-track-neg-2-5)",
    "neg-2": "var(--prim-track-neg-2)",
    "neg-1-8": "var(--prim-track-neg-1-8)",
    "neg-1-6": "var(--prim-track-neg-1-6)",
    "neg-1-4": "var(--prim-track-neg-1-4)",
    "neg-1-2": "var(--prim-track-neg-1-2)",
    "neg-1": "var(--prim-track-neg-1)",
    "neg-0-8": "var(--prim-track-neg-0-8)",
    "neg-0-6": "var(--prim-track-neg-0-6)",
    "neg-0-4": "var(--prim-track-neg-0-4)",
    "neg-0-2": "var(--prim-track-neg-0-2)",
    "neg-0-1": "var(--prim-track-neg-0-1)",
    "zero": "var(--prim-track-zero)",
    "pos-0-1": "var(--prim-track-pos-0-1)",
    "pos-0-2": "var(--prim-track-pos-0-2)",
    "pos-0-4": "var(--prim-track-pos-0-4)",
    "pos-0-6": "var(--prim-track-pos-0-6)",
    "pos-0-8": "var(--prim-track-pos-0-8)",
    "pos-1": "var(--prim-track-pos-1)",
    "pos-1-2": "var(--prim-track-pos-1-2)",
    "pos-1-4": "var(--prim-track-pos-1-4)",
    "pos-1-6": "var(--prim-track-pos-1-6)",
    "pos-1-8": "var(--prim-track-pos-1-8)",
    "pos-2": "var(--prim-track-pos-2)",
    "pos-4": "var(--prim-track-pos-4)",
    "pos-6": "var(--prim-track-pos-6)",
    "pos-8": "var(--prim-track-pos-8)",
    "pos-10": "var(--prim-track-pos-10)"
  },
  "primRatios": {
    "1-00": "var(--prim-ratios-1-00)",
    "1-05": "var(--prim-ratios-1-05)",
    "1-10": "var(--prim-ratios-1-10)",
    "1-15": "var(--prim-ratios-1-15)",
    "1-20": "var(--prim-ratios-1-20)",
    "1-25": "var(--prim-ratios-1-25)",
    "1-30": "var(--prim-ratios-1-30)",
    "1-35": "var(--prim-ratios-1-35)",
    "1-40": "var(--prim-ratios-1-40)",
    "1-45": "var(--prim-ratios-1-45)",
    "1-50": "var(--prim-ratios-1-50)",
    "1-55": "var(--prim-ratios-1-55)",
    "1-60": "var(--prim-ratios-1-60)",
    "1-65": "var(--prim-ratios-1-65)",
    "1-70": "var(--prim-ratios-1-70)",
    "1-75": "var(--prim-ratios-1-75)",
    "1-80": "var(--prim-ratios-1-80)",
    "1-85": "var(--prim-ratios-1-85)",
    "1-90": "var(--prim-ratios-1-90)",
    "1-95": "var(--prim-ratios-1-95)",
    "2-00": "var(--prim-ratios-2-00)"
  },
  "alCol": {
    "brand": {
      "1": "var(--al-col-brand-1)",
      "2": "var(--al-col-brand-2)",
      "3": "var(--al-col-brand-3)",
      "4": "var(--al-col-brand-4)",
      "5": "var(--al-col-brand-5)",
      "6": "var(--al-col-brand-6)",
      "7": "var(--al-col-brand-7)",
      "8": "var(--al-col-brand-8)",
      "9": "var(--al-col-brand-9)",
      "10": "var(--al-col-brand-10)",
      "11": "var(--al-col-brand-11)",
      "12": "var(--al-col-brand-12)"
    },
    "error": {
      "1": "var(--al-col-error-1)",
      "2": "var(--al-col-error-2)",
      "3": "var(--al-col-error-3)",
      "4": "var(--al-col-error-4)",
      "5": "var(--al-col-error-5)",
      "6": "var(--al-col-error-6)",
      "7": "var(--al-col-error-7)",
      "8": "var(--al-col-error-8)",
      "9": "var(--al-col-error-9)",
      "10": "var(--al-col-error-10)",
      "11": "var(--al-col-error-11)",
      "12": "var(--al-col-error-12)"
    },
    "warning": {
      "1": "var(--al-col-warning-1)",
      "2": "var(--al-col-warning-2)",
      "3": "var(--al-col-warning-3)",
      "4": "var(--al-col-warning-4)",
      "5": "var(--al-col-warning-5)",
      "6": "var(--al-col-warning-6)",
      "7": "var(--al-col-warning-7)",
      "8": "var(--al-col-warning-8)",
      "9": "var(--al-col-warning-9)",
      "10": "var(--al-col-warning-10)",
      "11": "var(--al-col-warning-11)",
      "12": "var(--al-col-warning-12)"
    },
    "info": {
      "1": "var(--al-col-info-1)",
      "2": "var(--al-col-info-2)",
      "3": "var(--al-col-info-3)",
      "4": "var(--al-col-info-4)",
      "5": "var(--al-col-info-5)",
      "6": "var(--al-col-info-6)",
      "7": "var(--al-col-info-7)",
      "8": "var(--al-col-info-8)",
      "9": "var(--al-col-info-9)",
      "10": "var(--al-col-info-10)",
      "11": "var(--al-col-info-11)",
      "12": "var(--al-col-info-12)"
    },
    "success": {
      "1": "var(--al-col-success-1)",
      "2": "var(--al-col-success-2)",
      "3": "var(--al-col-success-3)",
      "4": "var(--al-col-success-4)",
      "5": "var(--al-col-success-5)",
      "6": "var(--al-col-success-6)",
      "7": "var(--al-col-success-7)",
      "8": "var(--al-col-success-8)",
      "9": "var(--al-col-success-9)",
      "10": "var(--al-col-success-10)",
      "11": "var(--al-col-success-11)",
      "12": "var(--al-col-success-12)"
    },
    "neutral": {
      "1": "var(--al-col-neutral-1)",
      "2": "var(--al-col-neutral-2)",
      "3": "var(--al-col-neutral-3)",
      "4": "var(--al-col-neutral-4)",
      "5": "var(--al-col-neutral-5)",
      "6": "var(--al-col-neutral-6)",
      "7": "var(--al-col-neutral-7)",
      "8": "var(--al-col-neutral-8)",
      "9": "var(--al-col-neutral-9)",
      "10": "var(--al-col-neutral-10)",
      "11": "var(--al-col-neutral-11)",
      "12": "var(--al-col-neutral-12)"
    },
    "base": {
      "brand-black": "var(--al-col-base-brand-black)",
      "brand-white": "var(--al-col-base-brand-white)",
      "brand-black-constant": "var(--al-col-base-brand-black-constant)",
      "white": "var(--al-col-base-white)",
      "black": "var(--al-col-base-black)",
      "white-constant": "var(--al-col-base-white-constant)",
      "black-constant": "var(--al-col-base-black-constant)"
    }
  },
  "alDim": {
    "nano": {
      "xs": "var(--al-dim-nano-xs)",
      "s": "var(--al-dim-nano-s)",
      "m": "var(--al-dim-nano-m)",
      "l": "var(--al-dim-nano-l)",
      "xl": "var(--al-dim-nano-xl)",
      "2xl": "var(--al-dim-nano-2xl)"
    },
    "standard": {
      "xs": "var(--al-dim-standard-xs)",
      "xl": "var(--al-dim-standard-xl)",
      "s": "var(--al-dim-standard-s)",
      "m": "var(--al-dim-standard-m)",
      "l": "var(--al-dim-standard-l)"
    },
    "big": {
      "xs": "var(--al-dim-big-xs)",
      "s": "var(--al-dim-big-s)",
      "m": "var(--al-dim-big-m)",
      "l": "var(--al-dim-big-l)",
      "xl": "var(--al-dim-big-xl)",
      "2xl": "var(--al-dim-big-2xl)"
    },
    "huge": {
      "xs": "var(--al-dim-huge-xs)",
      "s": "var(--al-dim-huge-s)",
      "m": "var(--al-dim-huge-m)",
      "l": "var(--al-dim-huge-l)",
      "xl": "var(--al-dim-huge-xl)"
    },
    "none": "var(--al-dim-none)"
  },
  "alType": {
    "style": {
      "normal": {
        "extra-light": "var(--al-type-style-normal-extra-light)",
        "light": "var(--al-type-style-normal-light)",
        "regular": "var(--al-type-style-normal-regular)",
        "medium": "var(--al-type-style-normal-medium)",
        "semibold": "var(--al-type-style-normal-semibold)",
        "bold": "var(--al-type-style-normal-bold)",
        "extrabold": "var(--al-type-style-normal-extrabold)",
        "black": "var(--al-type-style-normal-black)"
      },
      "italic": {
        "italic": "var(--al-type-style-italic-italic)",
        "medium-italic": "var(--al-type-style-italic-medium-italic)",
        "semi-bold-italic": "var(--al-type-style-italic-semi-bold-italic)",
        "bold-italic": "var(--al-type-style-italic-bold-italic)"
      }
    },
    "family": {
      "brand": "var(--al-type-family-brand)",
      "deco": "var(--al-type-family-deco)",
      "primary": "var(--al-type-family-primary)",
      "secondary": "var(--al-type-family-secondary)",
      "tertiary": "var(--al-type-family-tertiary)"
    },
    "paragraph-spacing": {
      "0": "var(--al-type-paragraph-spacing-0)",
      "8": "var(--al-type-paragraph-spacing-8)",
      "12": "var(--al-type-paragraph-spacing-12)",
      "16": "var(--al-type-paragraph-spacing-16)"
    },
    "letter-spacing": {
      "neg-10": "var(--al-type-letter-spacing-neg-10)",
      "neg-8": "var(--al-type-letter-spacing-neg-8)",
      "neg-6": "var(--al-type-letter-spacing-neg-6)",
      "neg-4": "var(--al-type-letter-spacing-neg-4)",
      "neg-3-5": "var(--al-type-letter-spacing-neg-3-5)",
      "neg-3": "var(--al-type-letter-spacing-neg-3)",
      "neg-2-5": "var(--al-type-letter-spacing-neg-2-5)",
      "neg-2": "var(--al-type-letter-spacing-neg-2)",
      "neg-1-8": "var(--al-type-letter-spacing-neg-1-8)",
      "neg-1-6": "var(--al-type-letter-spacing-neg-1-6)",
      "neg-1-4": "var(--al-type-letter-spacing-neg-1-4)",
      "neg-1-2": "var(--al-type-letter-spacing-neg-1-2)",
      "neg-1": "var(--al-type-letter-spacing-neg-1)",
      "neg-0-8": "var(--al-type-letter-spacing-neg-0-8)",
      "neg-0-6": "var(--al-type-letter-spacing-neg-0-6)",
      "neg-0-4": "var(--al-type-letter-spacing-neg-0-4)",
      "neg-0-2": "var(--al-type-letter-spacing-neg-0-2)",
      "neg-0-1": "var(--al-type-letter-spacing-neg-0-1)",
      "zero": "var(--al-type-letter-spacing-zero)",
      "pos-0-1": "var(--al-type-letter-spacing-pos-0-1)",
      "pos-0-2": "var(--al-type-letter-spacing-pos-0-2)",
      "pos-0-4": "var(--al-type-letter-spacing-pos-0-4)",
      "pos-0-6": "var(--al-type-letter-spacing-pos-0-6)",
      "pos-0-8": "var(--al-type-letter-spacing-pos-0-8)",
      "pos-1": "var(--al-type-letter-spacing-pos-1)",
      "pos-1-2": "var(--al-type-letter-spacing-pos-1-2)",
      "pos-1-4": "var(--al-type-letter-spacing-pos-1-4)",
      "pos-1-6": "var(--al-type-letter-spacing-pos-1-6)",
      "pos-1-8": "var(--al-type-letter-spacing-pos-1-8)",
      "pos-2": "var(--al-type-letter-spacing-pos-2)",
      "pos-4": "var(--al-type-letter-spacing-pos-4)",
      "pos-6": "var(--al-type-letter-spacing-pos-6)",
      "pos-8": "var(--al-type-letter-spacing-pos-8)",
      "pos-10": "var(--al-type-letter-spacing-pos-10)"
    },
    "size": {
      "display": {
        "s": "var(--al-type-size-display-s)",
        "m": "var(--al-type-size-display-m)",
        "l": "var(--al-type-size-display-l)",
        "xl": "var(--al-type-size-display-xl)",
        "2xl": "var(--al-type-size-display-2xl)"
      },
      "text": {
        "xs": "var(--al-type-size-text-xs)",
        "s": "var(--al-type-size-text-s)",
        "m": "var(--al-type-size-text-m)",
        "l": "var(--al-type-size-text-l)",
        "xl": "var(--al-type-size-text-xl)"
      },
      "title": {
        "xs": "var(--al-type-size-title-xs)",
        "s": "var(--al-type-size-title-s)",
        "m": "var(--al-type-size-title-m)",
        "l": "var(--al-type-size-title-l)",
        "xl": "var(--al-type-size-title-xl)"
      },
      "deco": {
        "s": "var(--al-type-size-deco-s)",
        "m": "var(--al-type-size-deco-m)",
        "l": "var(--al-type-size-deco-l)",
        "xl": "var(--al-type-size-deco-xl)",
        "2xl": "var(--al-type-size-deco-2xl)"
      }
    },
    "line-height": {
      "display": {
        "s": "var(--al-type-line-height-display-s)",
        "m": "var(--al-type-line-height-display-m)",
        "l": "var(--al-type-line-height-display-l)",
        "xl": "var(--al-type-line-height-display-xl)",
        "2xl": "var(--al-type-line-height-display-2xl)",
        "3xl": "var(--al-type-line-height-display-3xl)"
      },
      "title": {
        "xs": "var(--al-type-line-height-title-xs)",
        "s": "var(--al-type-line-height-title-s)",
        "m": "var(--al-type-line-height-title-m)",
        "l": "var(--al-type-line-height-title-l)",
        "xl": "var(--al-type-line-height-title-xl)",
        "2xl": "var(--al-type-line-height-title-2xl)",
        "3xl": "var(--al-type-line-height-title-3xl)"
      },
      "text": {
        "xs": "var(--al-type-line-height-text-xs)",
        "s": "var(--al-type-line-height-text-s)",
        "m": "var(--al-type-line-height-text-m)",
        "l": "var(--al-type-line-height-text-l)",
        "xl": "var(--al-type-line-height-text-xl)",
        "2xl": "var(--al-type-line-height-text-2xl)",
        "3xl": "var(--al-type-line-height-text-3xl)"
      }
    }
  },
  "alRadii": {
    "none": "var(--al-radii-none)",
    "xxs": "var(--al-radii-xxs)",
    "xs": "var(--al-radii-xs)",
    "sm": "var(--al-radii-sm)",
    "md": "var(--al-radii-md)",
    "lg": "var(--al-radii-lg)",
    "xl": "var(--al-radii-xl)",
    "2xl": "var(--al-radii-2xl)",
    "3xl": "var(--al-radii-3xl)",
    "4xl": "var(--al-radii-4xl)",
    "full": "var(--al-radii-full)"
  },
  "alContainer": {
    "xxs": "var(--al-container-xxs)",
    "xs": "var(--al-container-xs)",
    "sm": "var(--al-container-sm)",
    "md": "var(--al-container-md)",
    "lg": "var(--al-container-lg)",
    "paragraph-max-width": "var(--al-container-paragraph-max-width)",
    "xl": "var(--al-container-xl)",
    "2xl": "var(--al-container-2xl)",
    "3xl": "var(--al-container-3xl)",
    "4xl": "var(--al-container-4xl)",
    "5xl": "var(--al-container-5xl)",
    "6xl": "var(--al-container-6xl)"
  },
  "alBreakpoints": {
    "xs": "var(--al-breakpoints-xs)",
    "sm": "var(--al-breakpoints-sm)",
    "md": "var(--al-breakpoints-md)",
    "lg": "var(--al-breakpoints-lg)",
    "xl": "var(--al-breakpoints-xl)",
    "2xl": "var(--al-breakpoints-2xl)",
    "3xl": "var(--al-breakpoints-3xl)",
    "4xl": "var(--al-breakpoints-4xl)"
  },
  "semCol": {
    "text": {
      "primary": "var(--sem-col-text-primary)",
      "primary-on-brand": "var(--sem-col-text-primary-on-brand)",
      "secondary": "var(--sem-col-text-secondary)",
      "secondary-hover": "var(--sem-col-text-secondary-hover)",
      "secondary-on-brand": "var(--sem-col-text-secondary-on-brand)",
      "tertiary": "var(--sem-col-text-tertiary)",
      "tertiary-hover": "var(--sem-col-text-tertiary-hover)",
      "tertiary-on-brand": "var(--sem-col-text-tertiary-on-brand)",
      "quaternary": "var(--sem-col-text-quaternary)",
      "quaternary-on-brand": "var(--sem-col-text-quaternary-on-brand)",
      "white": "var(--sem-col-text-white)",
      "disabled": "var(--sem-col-text-disabled)",
      "placeholder": "var(--sem-col-text-placeholder)",
      "placeholder-subtle": "var(--sem-col-text-placeholder-subtle)",
      "brand-primary": "var(--sem-col-text-brand-primary)",
      "brand-secondary": "var(--sem-col-text-brand-secondary)",
      "brand-secondary-hover": "var(--sem-col-text-brand-secondary-hover)",
      "brand-tertiary": "var(--sem-col-text-brand-tertiary)",
      "brand-tertiary-alt": "var(--sem-col-text-brand-tertiary-alt)",
      "error-primary": "var(--sem-col-text-error-primary)",
      "error-primary-hover": "var(--sem-col-text-error-primary-hover)",
      "warning-primary": "var(--sem-col-text-warning-primary)",
      "success-primary": "var(--sem-col-text-success-primary)"
    },
    "border": {
      "primary": "var(--sem-col-border-primary)",
      "secondary": "var(--sem-col-border-secondary)",
      "secondary-alt": "var(--sem-col-border-secondary-alt)",
      "tertiary": "var(--sem-col-border-tertiary)",
      "disabled": "var(--sem-col-border-disabled)",
      "disabled-subtle": "var(--sem-col-border-disabled-subtle)",
      "brand": "var(--sem-col-border-brand)",
      "brand-alt": "var(--sem-col-border-brand-alt)",
      "error": "var(--sem-col-border-error)",
      "error-subtle": "var(--sem-col-border-error-subtle)"
    },
    "fg": {
      "white": "var(--sem-col-fg-white)",
      "primary": "var(--sem-col-fg-primary)",
      "secondary": "var(--sem-col-fg-secondary)",
      "secondary-hover": "var(--sem-col-fg-secondary-hover)",
      "tertiary": "var(--sem-col-fg-tertiary)",
      "tertiary-hover": "var(--sem-col-fg-tertiary-hover)",
      "quaternary": "var(--sem-col-fg-quaternary)",
      "quaternary-hover": "var(--sem-col-fg-quaternary-hover)",
      "disabled": "var(--sem-col-fg-disabled)",
      "disabled-subtle": "var(--sem-col-fg-disabled-subtle)",
      "brand-primary": "var(--sem-col-fg-brand-primary)",
      "brand-primary-alt": "var(--sem-col-fg-brand-primary-alt)",
      "brand-secondary": "var(--sem-col-fg-brand-secondary)",
      "brand-secondary-alt": "var(--sem-col-fg-brand-secondary-alt)",
      "brand-secondary-hover": "var(--sem-col-fg-brand-secondary-hover)",
      "error-primary": "var(--sem-col-fg-error-primary)",
      "error-secondary": "var(--sem-col-fg-error-secondary)",
      "warning-primary": "var(--sem-col-fg-warning-primary)",
      "warning-secondary": "var(--sem-col-fg-warning-secondary)",
      "success-primary": "var(--sem-col-fg-success-primary)",
      "success-secondary": "var(--sem-col-fg-success-secondary)"
    },
    "bg": {
      "overlay": "var(--sem-col-bg-overlay)",
      "active": "var(--sem-col-bg-active)",
      "disabled": "var(--sem-col-bg-disabled)",
      "primary": "var(--sem-col-bg-primary)",
      "primary-solid": "var(--sem-col-bg-primary-solid)",
      "primary-alt": "var(--sem-col-bg-primary-alt)",
      "primary-hover": "var(--sem-col-bg-primary-hover)",
      "secondary": "var(--sem-col-bg-secondary)",
      "secondary-alt": "var(--sem-col-bg-secondary-alt)",
      "secondary-hover": "var(--sem-col-bg-secondary-hover)",
      "secondary-subtle": "var(--sem-col-bg-secondary-subtle)",
      "secondary-solid": "var(--sem-col-bg-secondary-solid)",
      "tertiary": "var(--sem-col-bg-tertiary)",
      "quaternary": "var(--sem-col-bg-quaternary)",
      "disabled-subtle": "var(--sem-col-bg-disabled-subtle)",
      "brand-primary": "var(--sem-col-bg-brand-primary)",
      "brand-primary-alt": "var(--sem-col-bg-brand-primary-alt)",
      "brand-secondary": "var(--sem-col-bg-brand-secondary)",
      "brand-solid": "var(--sem-col-bg-brand-solid)",
      "brand-solid-hover": "var(--sem-col-bg-brand-solid-hover)",
      "brand-section": "var(--sem-col-bg-brand-section)",
      "brand-section-subtle": "var(--sem-col-bg-brand-section-subtle)",
      "error-primary": "var(--sem-col-bg-error-primary)",
      "error-secondary": "var(--sem-col-bg-error-secondary)",
      "error-solid": "var(--sem-col-bg-error-solid)",
      "error-solid-hover": "var(--sem-col-bg-error-solid-hover)",
      "warning-primary": "var(--sem-col-bg-warning-primary)",
      "warning-secondary": "var(--sem-col-bg-warning-secondary)",
      "warning-solid": "var(--sem-col-bg-warning-solid)",
      "success-primary": "var(--sem-col-bg-success-primary)",
      "success-secondary": "var(--sem-col-bg-success-secondary)",
      "success-solid": "var(--sem-col-bg-success-solid)"
    }
  },
  "semDimFluid": {
    "nano": {
      "xs": "var(--sem-dim-fluid-nano-xs)",
      "s": "var(--sem-dim-fluid-nano-s)",
      "m": "var(--sem-dim-fluid-nano-m)",
      "l": "var(--sem-dim-fluid-nano-l)",
      "xl": "var(--sem-dim-fluid-nano-xl)",
      "2xl": "var(--sem-dim-fluid-nano-2xl)"
    },
    "standard": {
      "xs": "var(--sem-dim-fluid-standard-xs)",
      "s": "var(--sem-dim-fluid-standard-s)",
      "m": "var(--sem-dim-fluid-standard-m)",
      "l": "var(--sem-dim-fluid-standard-l)",
      "xl": "var(--sem-dim-fluid-standard-xl)"
    },
    "big": {
      "xs": "var(--sem-dim-fluid-big-xs)",
      "s": "var(--sem-dim-fluid-big-s)",
      "m": "var(--sem-dim-fluid-big-m)",
      "l": "var(--sem-dim-fluid-big-l)",
      "xl": "var(--sem-dim-fluid-big-xl)",
      "2xl": "var(--sem-dim-fluid-big-2xl)"
    },
    "huge": {
      "xs": "var(--sem-dim-fluid-huge-xs)",
      "s": "var(--sem-dim-fluid-huge-s)",
      "m": "var(--sem-dim-fluid-huge-m)",
      "l": "var(--sem-dim-fluid-huge-l)",
      "xl": "var(--sem-dim-fluid-huge-xl)"
    },
    "none": "var(--sem-dim-fluid-none)"
  },
  "semDimStatic": {
    "nano": {
      "xs": "var(--sem-dim-static-nano-xs)",
      "s": "var(--sem-dim-static-nano-s)",
      "m": "var(--sem-dim-static-nano-m)",
      "l": "var(--sem-dim-static-nano-l)",
      "xl": "var(--sem-dim-static-nano-xl)",
      "2xl": "var(--sem-dim-static-nano-2xl)"
    },
    "standard": {
      "xs": "var(--sem-dim-static-standard-xs)",
      "s": "var(--sem-dim-static-standard-s)",
      "m": "var(--sem-dim-static-standard-m)",
      "l": "var(--sem-dim-static-standard-l)",
      "xl": "var(--sem-dim-static-standard-xl)"
    },
    "big": {
      "xs": "var(--sem-dim-static-big-xs)",
      "s": "var(--sem-dim-static-big-s)",
      "m": "var(--sem-dim-static-big-m)",
      "l": "var(--sem-dim-static-big-l)",
      "xl": "var(--sem-dim-static-big-xl)",
      "2xl": "var(--sem-dim-static-big-2xl)"
    },
    "huge": {
      "xs": "var(--sem-dim-static-huge-xs)",
      "s": "var(--sem-dim-static-huge-s)",
      "m": "var(--sem-dim-static-huge-m)",
      "l": "var(--sem-dim-static-huge-l)",
      "xl": "var(--sem-dim-static-huge-xl)"
    },
    "none": "var(--sem-dim-static-none)"
  },
  "semTypeFluid": {
    "deco": {
      "2xl": {
        "font": "var(--sem-type-fluid-deco-2xl-font)",
        "style": "var(--sem-type-fluid-deco-2xl-style)",
        "size": "var(--sem-type-fluid-deco-2xl-size)",
        "line-height": "var(--sem-type-fluid-deco-2xl-line-height)",
        "letter-spacing": "var(--sem-type-fluid-deco-2xl-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-deco-2xl-paragraph-spacing)"
      },
      "xl": {
        "font": "var(--sem-type-fluid-deco-xl-font)",
        "style": "var(--sem-type-fluid-deco-xl-style)",
        "size": "var(--sem-type-fluid-deco-xl-size)",
        "line-height": "var(--sem-type-fluid-deco-xl-line-height)",
        "letter-spacing": "var(--sem-type-fluid-deco-xl-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-deco-xl-paragraph-spacing)"
      },
      "l": {
        "font": "var(--sem-type-fluid-deco-l-font)",
        "style": "var(--sem-type-fluid-deco-l-style)",
        "size": "var(--sem-type-fluid-deco-l-size)",
        "line-height": "var(--sem-type-fluid-deco-l-line-height)",
        "letter-spacing": "var(--sem-type-fluid-deco-l-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-deco-l-paragraph-spacing)"
      },
      "m": {
        "font": "var(--sem-type-fluid-deco-m-font)",
        "style": "var(--sem-type-fluid-deco-m-style)",
        "size": "var(--sem-type-fluid-deco-m-size)",
        "line-height": "var(--sem-type-fluid-deco-m-line-height)",
        "letter-spacing": "var(--sem-type-fluid-deco-m-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-deco-m-paragraph-spacing)"
      },
      "s": {
        "font": "var(--sem-type-fluid-deco-s-font)",
        "style": "var(--sem-type-fluid-deco-s-style)",
        "size": "var(--sem-type-fluid-deco-s-size)",
        "line-height": "var(--sem-type-fluid-deco-s-line-height)",
        "letter-spacing": "var(--sem-type-fluid-deco-s-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-deco-s-paragraph-spacing)"
      }
    },
    "display": {
      "2xl": {
        "font": "var(--sem-type-fluid-display-2xl-font)",
        "style": "var(--sem-type-fluid-display-2xl-style)",
        "size": "var(--sem-type-fluid-display-2xl-size)",
        "line-height": "var(--sem-type-fluid-display-2xl-line-height)",
        "letter-spacing": "var(--sem-type-fluid-display-2xl-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-display-2xl-paragraph-spacing)"
      },
      "xl": {
        "font": "var(--sem-type-fluid-display-xl-font)",
        "style": "var(--sem-type-fluid-display-xl-style)",
        "size": "var(--sem-type-fluid-display-xl-size)",
        "line-height": "var(--sem-type-fluid-display-xl-line-height)",
        "letter-spacing": "var(--sem-type-fluid-display-xl-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-display-xl-paragraph-spacing)"
      },
      "l": {
        "font": "var(--sem-type-fluid-display-l-font)",
        "style": "var(--sem-type-fluid-display-l-style)",
        "size": "var(--sem-type-fluid-display-l-size)",
        "line-height": "var(--sem-type-fluid-display-l-line-height)",
        "letter-spacing": "var(--sem-type-fluid-display-l-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-display-l-paragraph-spacing)"
      },
      "m": {
        "font": "var(--sem-type-fluid-display-m-font)",
        "style": "var(--sem-type-fluid-display-m-style)",
        "size": "var(--sem-type-fluid-display-m-size)",
        "line-height": "var(--sem-type-fluid-display-m-line-height)",
        "letter-spacing": "var(--sem-type-fluid-display-m-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-display-m-paragraph-spacing)"
      },
      "s": {
        "font": "var(--sem-type-fluid-display-s-font)",
        "style": "var(--sem-type-fluid-display-s-style)",
        "size": "var(--sem-type-fluid-display-s-size)",
        "line-height": "var(--sem-type-fluid-display-s-line-height)",
        "letter-spacing": "var(--sem-type-fluid-display-s-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-display-s-paragraph-spacing)"
      }
    },
    "title": {
      "screen": {
        "primary": {
          "font": "var(--sem-type-fluid-title-screen-primary-font)",
          "style": "var(--sem-type-fluid-title-screen-primary-style)",
          "size": "var(--sem-type-fluid-title-screen-primary-size)",
          "line-height": "var(--sem-type-fluid-title-screen-primary-line-height)",
          "letter-spacing": "var(--sem-type-fluid-title-screen-primary-letter-spacing)",
          "paragraph-spacing": "var(--sem-type-fluid-title-screen-primary-paragraph-spacing)"
        },
        "secondary": {
          "font": "var(--sem-type-fluid-title-screen-secondary-font)",
          "style": "var(--sem-type-fluid-title-screen-secondary-style)",
          "size": "var(--sem-type-fluid-title-screen-secondary-size)",
          "line-height": "var(--sem-type-fluid-title-screen-secondary-line-height)",
          "letter-spacing": "var(--sem-type-fluid-title-screen-secondary-letter-spacing)",
          "paragraph-spacing": "var(--sem-type-fluid-title-screen-secondary-paragraph-spacing)"
        }
      },
      "section": {
        "primary": {
          "font": "var(--sem-type-fluid-title-section-primary-font)",
          "style": "var(--sem-type-fluid-title-section-primary-style)",
          "size": "var(--sem-type-fluid-title-section-primary-size)",
          "line-height": "var(--sem-type-fluid-title-section-primary-line-height)",
          "letter-spacing": "var(--sem-type-fluid-title-section-primary-letter-spacing)",
          "paragraph-spacing": "var(--sem-type-fluid-title-section-primary-paragraph-spacing)"
        },
        "secondary": {
          "font": "var(--sem-type-fluid-title-section-secondary-font)",
          "style": "var(--sem-type-fluid-title-section-secondary-style)",
          "size": "var(--sem-type-fluid-title-section-secondary-size)",
          "line-height": "var(--sem-type-fluid-title-section-secondary-line-height)",
          "letter-spacing": "var(--sem-type-fluid-title-section-secondary-letter-spacing)",
          "paragraph-spacing": "var(--sem-type-fluid-title-section-secondary-paragraph-spacing)"
        }
      },
      "product": {
        "primary": {
          "font": "var(--sem-type-fluid-title-product-primary-font)",
          "style": "var(--sem-type-fluid-title-product-primary-style)",
          "size": "var(--sem-type-fluid-title-product-primary-size)",
          "line-height": "var(--sem-type-fluid-title-product-primary-line-height)",
          "letter-spacing": "var(--sem-type-fluid-title-product-primary-letter-spacing)",
          "paragraph-spacing": "var(--sem-type-fluid-title-product-primary-paragraph-spacing)"
        },
        "secondary": {
          "font": "var(--sem-type-fluid-title-product-secondary-font)",
          "style": "var(--sem-type-fluid-title-product-secondary-style)",
          "size": "var(--sem-type-fluid-title-product-secondary-size)",
          "line-height": "var(--sem-type-fluid-title-product-secondary-line-height)",
          "letter-spacing": "var(--sem-type-fluid-title-product-secondary-letter-spacing)",
          "paragraph-spacing": "var(--sem-type-fluid-title-product-secondary-paragraph-spacing)"
        }
      },
      "headline": {
        "font": "var(--sem-type-fluid-title-headline-font)",
        "style": "var(--sem-type-fluid-title-headline-style)",
        "size": "var(--sem-type-fluid-title-headline-size)",
        "line-height": "var(--sem-type-fluid-title-headline-line-height)",
        "letter-spacing": "var(--sem-type-fluid-title-headline-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-title-headline-paragraph-spacing)"
      }
    },
    "body": {
      "heading": {
        "font": "var(--sem-type-fluid-body-heading-font)",
        "style": "var(--sem-type-fluid-body-heading-style)",
        "size": "var(--sem-type-fluid-body-heading-size)",
        "line-height": "var(--sem-type-fluid-body-heading-line-height)",
        "letter-spacing": "var(--sem-type-fluid-body-heading-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-body-heading-paragraph-spacing)"
      },
      "normal": {
        "font": "var(--sem-type-fluid-body-normal-font)",
        "style": "var(--sem-type-fluid-body-normal-style)",
        "size": "var(--sem-type-fluid-body-normal-size)",
        "line-height": "var(--sem-type-fluid-body-normal-line-height)",
        "letter-spacing": "var(--sem-type-fluid-body-normal-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-body-normal-paragraph-spacing)"
      },
      "strong": {
        "font": "var(--sem-type-fluid-body-strong-font)",
        "style": "var(--sem-type-fluid-body-strong-style)",
        "size": "var(--sem-type-fluid-body-strong-size)",
        "line-height": "var(--sem-type-fluid-body-strong-line-height)",
        "letter-spacing": "var(--sem-type-fluid-body-strong-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-body-strong-paragraph-spacing)"
      },
      "caption": {
        "font": "var(--sem-type-fluid-body-caption-font)",
        "style": "var(--sem-type-fluid-body-caption-style)",
        "size": "var(--sem-type-fluid-body-caption-size)",
        "line-height": "var(--sem-type-fluid-body-caption-line-height)",
        "letter-spacing": "var(--sem-type-fluid-body-caption-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-body-caption-paragraph-spacing)"
      }
    },
    "label": {
      "xl": {
        "font": "var(--sem-type-fluid-label-xl-font)",
        "style": "var(--sem-type-fluid-label-xl-style)",
        "size": "var(--sem-type-fluid-label-xl-size)",
        "line-height": "var(--sem-type-fluid-label-xl-line-height)",
        "letter-spacing": "var(--sem-type-fluid-label-xl-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-label-xl-paragraph-spacing)"
      },
      "l": {
        "font": "var(--sem-type-fluid-label-l-font)",
        "style": "var(--sem-type-fluid-label-l-style)",
        "size": "var(--sem-type-fluid-label-l-size)",
        "line-height": "var(--sem-type-fluid-label-l-line-height)",
        "letter-spacing": "var(--sem-type-fluid-label-l-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-label-l-paragraph-spacing)"
      },
      "m": {
        "font": "var(--sem-type-fluid-label-m-font)",
        "style": "var(--sem-type-fluid-label-m-style)",
        "size": "var(--sem-type-fluid-label-m-size)",
        "line-height": "var(--sem-type-fluid-label-m-line-height)",
        "letter-spacing": "var(--sem-type-fluid-label-m-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-label-m-paragraph-spacing)"
      },
      "s": {
        "font": "var(--sem-type-fluid-label-s-font)",
        "style": "var(--sem-type-fluid-label-s-style)",
        "size": "var(--sem-type-fluid-label-s-size)",
        "line-height": "var(--sem-type-fluid-label-s-line-height)",
        "letter-spacing": "var(--sem-type-fluid-label-s-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-label-s-paragraph-spacing)"
      },
      "xs": {
        "font": "var(--sem-type-fluid-label-xs-font)",
        "style": "var(--sem-type-fluid-label-xs-style)",
        "size": "var(--sem-type-fluid-label-xs-size)",
        "line-height": "var(--sem-type-fluid-label-xs-line-height)",
        "letter-spacing": "var(--sem-type-fluid-label-xs-letter-spacing)",
        "paragraph-spacing": "var(--sem-type-fluid-label-xs-paragraph-spacing)"
      }
    }
  },
  "semBorder": {
    "xs": "var(--sem-border-xs)",
    "s": "var(--sem-border-s)",
    "m": "var(--sem-border-m)",
    "l": "var(--sem-border-l)",
    "xl": "var(--sem-border-xl)"
  },
  "semRadii": {
    "none": "var(--sem-radii-none)",
    "xxs": "var(--sem-radii-xxs)",
    "xs": "var(--sem-radii-xs)",
    "sm": "var(--sem-radii-sm)",
    "md": "var(--sem-radii-md)",
    "lg": "var(--sem-radii-lg)",
    "xl": "var(--sem-radii-xl)",
    "2xl": "var(--sem-radii-2xl)",
    "3xl": "var(--sem-radii-3xl)",
    "4xl": "var(--sem-radii-4xl)",
    "full": "var(--sem-radii-full)"
  },
  "semContainer": {
    "xxs": "var(--sem-container-xxs)",
    "xs": "var(--sem-container-xs)",
    "sm": "var(--sem-container-sm)",
    "md": "var(--sem-container-md)",
    "lg": "var(--sem-container-lg)",
    "xl": "var(--sem-container-xl)",
    "2xl": "var(--sem-container-2xl)",
    "3xl": "var(--sem-container-3xl)",
    "4xl": "var(--sem-container-4xl)",
    "5xl": "var(--sem-container-5xl)",
    "6xl": "var(--sem-container-6xl)",
    "max-width": "var(--sem-container-max-width)",
    "paragraph-max-width": "var(--sem-container-paragraph-max-width)"
  },
  "semBreakpoints": {
    "xs": "var(--sem-breakpoints-xs)",
    "sm": "var(--sem-breakpoints-sm)",
    "md": "var(--sem-breakpoints-md)",
    "lg": "var(--sem-breakpoints-lg)",
    "xl": "var(--sem-breakpoints-xl)",
    "2xl": "var(--sem-breakpoints-2xl)",
    "3xl": "var(--sem-breakpoints-3xl)",
    "4xl": "var(--sem-breakpoints-4xl)"
  },
  "com": {
    "controls": {
      "icon": "var(--com-controls-icon)"
    },
    "tabbar": {
      "icon": "var(--com-tabbar-icon)",
      "surface": "var(--com-tabbar-surface)",
      "label": "var(--com-tabbar-label)"
    }
  },
  "effects": {
    "shadow-xs": "var(--effects-shadow-xs)",
    "shadow-sm-01": "var(--effects-shadow-sm-01)",
    "shadow-sm-02": "var(--effects-shadow-sm-02)",
    "shadow-md-01": "var(--effects-shadow-md-01)",
    "shadow-md-02": "var(--effects-shadow-md-02)",
    "shadow-lg-01": "var(--effects-shadow-lg-01)",
    "shadow-lg-02": "var(--effects-shadow-lg-02)",
    "shadow-lg-03": "var(--effects-shadow-lg-03)",
    "shadow-xl-01": "var(--effects-shadow-xl-01)",
    "shadow-xl-02": "var(--effects-shadow-xl-02)",
    "shadow-xl-03": "var(--effects-shadow-xl-03)",
    "shadow-2xl-01": "var(--effects-shadow-2xl-01)",
    "shadow-2xl-02": "var(--effects-shadow-2xl-02)",
    "shadow-3xl-01": "var(--effects-shadow-3xl-01)",
    "shadow-3xl-02": "var(--effects-shadow-3xl-02)",
    "shadow-skeumorphic-inner": "var(--effects-shadow-skeumorphic-inner)",
    "shadow-skeumorphic-inner-border": "var(--effects-shadow-skeumorphic-inner-border)",
    "blur-sm": "var(--effects-blur-sm)",
    "blur-md": "var(--effects-blur-md)",
    "blur-lg": "var(--effects-blur-lg)",
    "blur-xl": "var(--effects-blur-xl)"
  }
} as const;
