import './tokens.css';
// Generated by figma-to-code — route wrapper (SPEC §3.1 output placement).
import './fonts.css';
import './theme.css';
import Editor402IphoneAppleBlurGlass from './Editor402IphoneAppleBlurGlass';

export default function Page() {
  return <Editor402IphoneAppleBlurGlass />;
}
