import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import {
  GRID_ENGINE_CACHE_VERSION,
  GRID_ENGINE_POLICY_SIGNATURE,
  handleGridJob,
  type GridDensity,
  type GridJob,
  type StandardLadderShape,
} from '@/lib/effect/grid'

const shapes: readonly StandardLadderShape[] = [
  'square',
  'circle',
  'triangle',
  'diamondShape',
]
const densities: readonly GridDensity[] = ['standard', 'light']

const jobs: GridJob[] = shapes.flatMap((shape) => densities.map((density) => ({
  operation: 'ladder' as const,
  recipe: { kind: 'standard' as const, shape },
  mode: 'standard' as const,
  options: { source: 'std' as const, density, center: 'centroid' as const },
})))

const entries = jobs.map((job) => ({ job, result: handleGridJob(job) }))
const output = `/* This file is generated by npm run grid:catalogue:generate. Do not edit by hand. */
import type { GridJob, GridJobResult } from './grid'

export const GRID_STATIC_CATALOGUE_CACHE_VERSION = ${GRID_ENGINE_CACHE_VERSION} as const
export const GRID_STATIC_CATALOGUE_POLICY_SIGNATURE = ${JSON.stringify(GRID_ENGINE_POLICY_SIGNATURE)} as const
export const GRID_STATIC_CATALOGUE_ENTRIES = ${JSON.stringify(entries, null, 2)} as const satisfies ReadonlyArray<{
  job: GridJob
  result: GridJobResult
}>
`

const target = fileURLToPath(new URL(
  '../src/lib/effect/grid-static-catalogue.generated.ts',
  import.meta.url,
))
await writeFile(target, output)
console.log(`Wrote ${entries.length} static Grid Lab catalogues to ${target}`)
