/** Generated by scripts/build.mjs. The hash covers every executable .js file in
 * this package except artifact-manifest.js itself, avoiding a self-referential digest. */
export const LOGIC_ARTIFACT_ID = "magnetic-logic-ts-v1";
export const LOGIC_ARTIFACT_HASH = "43ffeb4186f62bed80d5b837fb99f6cbbdf434c45e7d99edd337e224a1d14719";
