/** Generated by scripts/build.mjs. The hash covers every executable .js file in
 * this package except artifact-manifest.js itself, avoiding a self-referential digest. */
export const LOGIC_ARTIFACT_ID = "magnetic-logic-ts-v1";
export const LOGIC_ARTIFACT_HASH = "e9759cec8935e65f97192a0c3d76342e1c12037e644c4aa89a547e1109a53e4c";
