/** Generated by scripts/build.mjs. The hash covers every executable .js file in
 * this package except artifact-manifest.js itself, avoiding a self-referential digest. */
export const LOGIC_ARTIFACT_ID = "magnetic-logic-ts-v1";
export const LOGIC_ARTIFACT_HASH = "093ab13d8076300fbf96eb484ae356b5273bc1e31990098ecd51cce13bace916";
